import type { Lesson, LessonStep, LessonStepKind } from './course';

const text = (tr: string) => ({ tr, en: tr });
const list = (tr: string[]) => ({ tr, en: tr });
type StepInput = [string, LessonStepKind, string, number, number, string, string, string, string[], string];
const step = ([id, kind, activity, duration, xp, title, description, objective, bullets, transition]: StepInput): LessonStep => ({
  id, kind, activity, duration, xp, title:text(title), description:text(description), objective:text(objective), bullets:list(bullets), transition:text(transition),
});

const lesson4Steps: LessonStep[] = [
  step(['l4-recall','prepare','route',5,20,'Sürüm, kök ve araçları geri çağır','Hub, Editor sürümü ve proje kökü tek bir oluşturma zincirinde buluşur. Önceki iki dersteki kararları doğru sıraya yeniden yerleştir.','Hub → sürüm → proje kökü → Editor ilişkisini kanıtla kurar.',['Hub projeyi ve Editor kurulumlarını yönetir','6000.6.x ifadesindeki patch kurum tarafından sabitlenir','Assets değil, onu taşıyan üst klasör proje köküdür'],'Şimdi projenin başlangıç kutusunu, yani template’i açacağız.']),
  step(['l4-template','teach','layers',7,35,'Template hazır oyun değildir','Template; başlangıç ayarları, paketler ve bazen örnek bir sahne sunar. Özgün mekanik, bölüm ve karakteri sen üretirsin.','Template, sample ve öğrenci üretimi içeriği katmanlarına ayırır.',['Ayar ve paket template katmanıdır','Sample bir özelliği göstermek için eklenen örnektir','Bitmiş bölüm ve özgün karakter template’in hazır ürünü değildir'],'Şablonun altında görüntüyü işleyen pipeline kararını inceleyelim.']),
  step(['l4-pipeline','simulate','compare',8,40,'Render pipeline seçimi','Built-in, URP ve HDRP yalnızca kalite düğmeleri değildir; shader ve özellik uyumluluğunu etkileyen farklı görüntüleme yollarıdır. Kursun başlangıç yolu URP’dir.','Üç proje hedefini uygun render pipeline ile eşleştirir.',['URP mobil ve orta seviye PC için dengeli başlangıçtır','Built-in eski içerik ağırlıklı projelerde görülebilir','HDRP yüksek doğruluk hedefidir; her cihazda otomatik olarak daha iyi değildir'],'Doğru pipeline’ın doğru Editor sürümüyle açıldığını doğrulayalım.']),
  step(['l4-version','practice','version',6,35,'Projenin Editor sürümünü sabitle','“Latest” en güvenli seçim değildir. Kursun tam major, minor ve patch değeri ekran, paket ve ekip uyumunu korur.','Sürüm anatomisini okuyup course version etiketli sürümü seçer.',['Major ürün ailesidir','Minor özellik hattıdır','Patch hata düzeltme ve uyumluluk seviyesidir'],'Sürüm hazır; şimdi anlaşılır bir proje adı üretelim.']),
  step(['l4-name','practice','validator',6,30,'Proje adını belirle','İyi proje adı kısa, anlamlı ve tutarlıdır. `LevelUpPractice` altı ay sonra da anlaşılır; `oyunfinalson3` sürüm karmaşası üretir.','Canlı doğrulayıcıda güvenli ve anlamlı proje adı üretir.',['Tam kelimeler kullan','Riskli karakter ve aşırı uzunluktan kaçın','Proje kimliği ile yedek tarihini birbirine karıştırma'],'İyi ad, yanlış konumda oluşturulursa yine sorun çıkarır.']),
  step(['l4-location','debug','tree',8,45,'Güvenli kayıt konumu','Location üst klasördür; proje adı bunun altında yeni kökü üretir. Başka bir Unity projesinin Assets klasörü içine proje kurulmaz.','Dosya ağacında güvenli üst klasörü seçip sonuç yolunu tahmin eder.',['D:/GameDev/Projects güvenli üst klasör örneğidir','ZIP içi çalışma konumu değildir','Sistem klasörü ve başka projenin Assets’i risklidir'],'Konum tamam; cloud hizmetlerinin zorunlu olup olmadığını ayıralım.']),
  step(['l4-cloud','simulate','toggle',5,30,'Yerel ve cloud proje ayrımı','Yerel Unity projesi oluşturmak ile isteğe bağlı cloud hizmetlerine bağlanmak farklı kararlardır. Hesap ekranındaki her seçenek başarı şartı değildir.','Cloud anahtarının yerel dosyalar ve ek servisler üzerindeki etkisini açıklar.',['Temel proje yerel diskte yaşayabilir','Cloud ek kurulum ve hesap adımları doğurabilir','Kapalı cloud seçeneği projenin geçersiz olduğu anlamına gelmez'],'Create’e basmadan önce bütün kararları tek manifestte görelim.']),
  step(['l4-summary','practice','manifest',6,35,'Oluşturmadan önce son kontrol','Editor sürümü, template, pipeline, ad, location ve cloud kararı tek bir proje manifestinde birbiriyle tutarlı olmalıdır.','Manifestteki kasıtlı çelişkiyi kanıtıyla bulur.',['URP template kurs sürümüyle açılmalıdır','Sonuç yolu başka bir proje içine düşmemelidir','İsteğe bağlı servis zorunlu alan gibi davranmamalıdır'],'Manifest tutarlı; şimdi oluşturma akışını çalıştıralım.']),
  step(['l4-create','simulate','form',8,40,'Create project akışı','New project ekranında sürüm, template, ad ve location birbirinden bağımsız fakat birlikte doğrulanan alanlardır.','Sanal Hub formunu eksiksiz doldurup proje manifesti üretir.',['Önce Editor sürümünü doğrula','Template ve pipeline hedefle uyuşmalı','Ad ile location birleşince sonuç kökü görünmelidir','Eksik alan açıklamasız kilit oluşturmaz'],'İlk açılışta beklemek, uygulamanın donduğu anlamına gelmez.']),
  step(['l4-first-open','observe','process',7,35,'İlk import’u anlamak','İlk açılışta paket bağımlılıkları çözülür, asset’ler Unity biçimine hazırlanır ve yerel cache kurulur. Bu süreç otomatik cloud yüklemesi değildir.','İlk açılış evrelerini ve her evredeki güvenli kararı sıralar.',['Package resolution bağımlılıkları hazırlar','Import kaynak veriyi Unity’nin kullanacağı biçime dönüştürür','Uzun süren işlemde durumu izle; zorla kapatmayı ilk seçenek yapma'],'Editor açıldı; yalnız görüntüye değil bağımsız kanıtlara bakalım.']),
  step(['l4-verify','test','hotspot',7,45,'Açılan projeyi kanıtla','Doğru açılışı sürüm, proje yolu, Hierarchy, Project ve Console gibi birbirinden bağımsız kanıtlarla doğrularız.','Editor maketindeki beş kanıt bölgesini bulup neyi kanıtladığını açıklar.',['Sürüm başlığı doğru olmalı','Project penceresinde Assets görünmeli','Hierarchy başlangıç sahnesini göstermeli','Console’da engelleyici hata bulunmamalı'],'Eksik kanıtta yanlış projeyi veya yanlış sürümü teşhis edeceğiz.']),
  step(['l4-debug','debug','diagnostic',7,50,'Yanlış proje kliniği','Belirtiyi gördüğün yerde rastgele işlem yapmak yerine kanıt → kök neden → en küçük güvenli düzeltme zinciri kur.','Altı proje açılış vakasında ilk kırık kanıtı teşhis eder.',['Yanlış Editor sürümü','Assets klasörünü proje diye açma','İç içe proje','Template veya package hazırlığı hatası','Yetersiz disk alanı'],'Şimdi bütün kararları Proje Fırlatma Merkezi’nde birleştir.']),
  step(['l4-game','game','mission',7,45,'Proje Fırlatma Merkezi','Üç görev için sürüm, template, ad ve konumu seç; manifest ışıklarını doğrula ve sanal projeyi güvenle fırlat.','Üç farklı proje brifinde tutarlı manifest üretir.',['2D prototip görevini oku','URP 3D eğitim hedefini kur','İç içe klasör riskini kurtar','Son görevde bütün kanıtları ilk denemede yakala'],'Finalde proje kurulum kararlarını yeni senaryolara aktar.']),
  step(['l4-finale','finale','finale',9,175,'Etkinlik Bombası','On iki karma turda template, pipeline, sürüm, ad, konum, cloud, import ve açılış tanısını bağımsız uygula.','Proje oluşturma hedeflerinde en az yüzde 70 ilk deneme başarısı gösterir.',['Tüm turlar tamamlanır','İki debug turu kanıt zinciri ister','Boss turunda tam manifest kurulur'],'İlk proje hazır; sırada Editor’ün çalışma alanları var.']),
];

const lesson5Steps: LessonStep[] = [
  step(['l5-recall','prepare','evidence',5,20,'Projeyi açtığını kanıtla','Dünkü proje yalnız “ekranda açıldı” diye doğrulanmaz. Sürüm, yol, Assets, Hierarchy ve Console kanıtlarını yeniden bul.','Beş açılış kanıtını ilgili Editor bölgesinde işaretler.',['Sürüm ve proje adı üst çubukta','Assets Project penceresinde','Sahne nesneleri Hierarchy’de','Engelleyici hatalar Console’da'],'Kanıtların bulunduğu altı ana çalışma alanını kuşbakışı görelim.']),
  step(['l5-map','observe','map',7,35,'Editor kuşbakışı haritası','Scene, Game, Hierarchy, Inspector, Project ve Console farklı sorulara cevap veren ama aynı proje üzerinde çalışan alanlardır.','Altı paneli konumu, sorusu ve komşu veri ilişkisiyle tanır.',['Scene: nerede düzenlerim?','Game: oyuncu ne görür?','Hierarchy: sahnede kim var?','Inspector: seçilenin özellikleri ne?','Project: hangi asset’ler var?','Console: ne oldu veya hata var mı?'],'Scene ve Game görünüşte benzer olsa da aynı kamera değildir.']),
  step(['l5-scene-game','simulate','viewport',8,45,'Scene ve Game ayrımı','Scene geliştiricinin serbest düzenleme bakışıdır; Game etkin kameranın oyuncuya sunduğu çıktıdır. Scene’de dolaşmak Game kamerasını kendiliğinden değiştirmez.','Bağlı iki viewportta gözlem kamerası ile oyun kamerasını ayırır.',['Scene bakış açısı serbesttir','Game kamera kadrajına bağlıdır','Scene’de görünen nesne Game’de kadraj dışında olabilir'],'Sahnedeki nesneleri listeleyen Hierarchy’ye geçelim.']),
  step(['l5-hierarchy','teach','hierarchy',7,40,'Hierarchy: sahnedeki kimler?','Hierarchy bilgisayar dosyalarını değil, açık sahnedeki GameObject’leri ve temel üst–alt ilişkileri gösterir.','Sahnedeki hedef nesneyi ARIA ağaç yapısından seçer.',['Camera, Light ve Ground sahne nesneleridir','Bir asset ile sahnedeki instance aynı şey değildir','Parent–child ayrıntısı Ders 6’da açılır'],'Dosya ve asset dünyası Project penceresindedir.']),
  step(['l5-project','teach','browser',7,40,'Project: hangi dosyalar var?','Project penceresi Assets içindeki sahne, material, model ve diğer proje varlıklarını tarar. Aynı asset sahnede birden fazla instance üretebilir.','Sanal asset tarayıcısında doğru klasör ve dosyayı bulur.',['Scenes sahne asset’lerini taşır','Materials görsel özellik varlıklarını taşır','Models kaynak geometriyi taşır','Project ile Hierarchy aynı liste değildir'],'Bir öğe seçildiğinde Inspector’ın neden değiştiğini izleyelim.']),
  step(['l5-inspector','simulate','inspector',8,45,'Inspector seçime göre değişir','Inspector sabit bir ayar kutusu değildir; Hierarchy’den nesne veya Project’ten asset seçimine göre başlığı ve düzenlenebilir alanları değişir.','Üç farklı seçimde Inspector’ın ortak ve değişen bölümlerini işaretler.',['Light seçimi Light Component alanlarını açar','Material seçimi asset özelliklerini açar','Transform sahne nesnelerinde temel uzamsal bilgidir'],'Panelleri tanıdın; şimdi Scene içinde kontrollü dolaş.']),
  step(['l5-navigation','practice','navigation',10,55,'Scene navigasyonu','Orbit hedefin etrafında döner, pan görünümü yana taşır, zoom yaklaşır ve focus seçili nesneyi merkeze getirir. Bunlar nesnenin Transform’unu değiştirmez.','Hedef nesneyi bulur; focus, orbit, pan ve zoom hareketlerini ayırır.',['Focus seçileni merkeze alır','Zoom kamera görüşünü değiştirir; Scale değildir','Orbit nesnenin çevresindeki bakışı değiştirir','Pan görünümü paralel taşır'],'Düzenleme bakışından Play Mode durumuna geçelim.']),
  step(['l5-toolbar-play','simulate','machine',7,40,'Toolbar ve Play Mode','Play, Pause ve Step farklı çalışma durumlarıdır. Play Mode sırasında yapılan bazı değişiklikler durdurunca kalıcı olmayabilir.','Edit, play, pause ve step durumlarını güvenli sırayla çalıştırır.',['Edit Mode kalıcı düzenleme alanıdır','Play Mode runtime simülasyonudur','Pause zamanı durdurur','Step tek ilerleme dilimi gösterir'],'Çalışan oyunun mesajlarını Console’da ayıralım.']),
  step(['l5-console','practice','filter',7,40,'Console mesajlarını ayır','Log bilgi verir, warning dikkat ister, error çalışmayı engelleyebilecek sorun bildirir. Clear mesajı kaldırır; kök nedeni düzeltmez.','On iki mesajı filtreleyip error kayıtlarını kanıtıyla ayırır.',['Renk tek bilgi kanalı değildir','Collapse benzer mesajları gruplar','Clear düzeltme işlemi değildir','Filtre görünmeyeni silmez'],'Aynı filtre mantığını kalabalık panel listelerinde kullanalım.']),
  step(['l5-search','practice','search',6,35,'Arama ve filtreyle kaybolmamak','Hierarchy araması sahne nesnelerini, Project araması asset’leri süzer. Sıfır sonuç öğenin silindiğini değil filtrenin eşleşmediğini gösterebilir.','Canlı aramada doğru kapsamı seçip kayıp görünen öğeyi bulur.',['`cam` Camera’yı bulabilir','Project ve Hierarchy farklı veri kümeleridir','Filtreyi temizlemek bütün öğeleri geri gösterir'],'Şimdi panel yerleşimini güvenle değiştirelim.']),
  step(['l5-layout','practice','dock',7,45,'Paneli taşı, kapat, geri getir','Panel yerleşimi proje içeriği değildir. Bir panel taşınabilir, kapatılabilir ve Window/Layout üzerinden geri getirilebilir.','Docking simülatöründe paneli taşıyıp varsayılan layout’u geri yükler.',['Hedef bölgeler taşıma sırasında görünür','Yanlış yerleşim geri alınabilir','Layout reset asset’leri silmez'],'Görevden doğru başlangıç paneline giden yolu seçelim.']),
  step(['l5-debug','debug','diagnostic',7,50,'Yanlış panel dedektifi','Her sorun aynı panelden çözülmez. Görevin sorduğu kanıtı belirleyip ilk paneli, sonra doğrulama panelini seç.','Altı görevde doğru panel rotasını kanıtla kurar.',['Sahne nesnesi için Hierarchy','Asset için Project','Seçili özellik için Inspector','Oyuncu çıktısı için Game','Hata kaydı için Console','Kayıp panel için Window/Layout'],'Şimdi altı bölgeyi Editor Kontrol Odası’nda kullan.']),
  step(['l5-game','game','mission',7,45,'Editor Kontrol Odası','Kamerayı seç, oyuncu görünümünü aç, material asset’ini bul, error filtresini çalıştır, hedefe odaklan ve layout’u kurtar.','Altı paneli ardışık görevlerde doğru amaçla kullanır.',['Her görev farklı panelden başlar','İlk hatada panelin görevi hatırlatılır','Hızdan önce doğru kanıt ölçülür'],'Finalde panel görevlerini karışık hâlde bağımsız çöz.']),
  step(['l5-finale','finale','finale',11,165,'Etkinlik Bombası','On iki karma turda panel görevleri, Scene/Game, asset/instance, navigasyon, Play Mode, Console ve layout kararlarını uygula.','Editor haritasında en az yüzde 70 ilk deneme başarısı gösterir.',['Altı panel görevi','Scene ve Game ayrımı','Console filtre tanısı','Layout boss görevi'],'Editor haritası hazır; sırada sahnenin gerçek yapı taşları var.']),
];

const lesson6Steps: LessonStep[] = [
  step(['l6-recall','prepare','route',5,20,'Editor pusulasını yeniden kur','Nesneyi seçme, özelliği değiştirme, sonucu görme ve sahne dosyasını bulma görevleri dört farklı Editor bölgesine uzanır.','Hierarchy → Inspector → Scene → Project görev rotasını kurar.',['Hierarchy nesneyi seçer','Inspector veriyi değiştirir','Scene sonucu gösterir','Project sahne asset’ini saklar'],'Bu rotada taşıdığımız temel varlığa GameObject denir.']),
  step(['l6-gameobject','teach','object',7,35,'GameObject: sahnedeki taşıyıcı','GameObject çizilen model veya kod değildir; isim, aktiflik, Transform ve başka Component’leri taşıyan sahne varlığıdır. Boş GameObject görünmeyebilir ama varlığını sürdürür.','Camera, Light, Cube ve boş GameObject’in ortak temelini ayırır.',['Hepsinde GameObject kimliği vardır','Transform her GameObject’te bulunur','Farklı görevleri farklı Component’ler üretir','Renderer çıkınca GameObject silinmez'],'Taşıyıcıya görev veren Component’leri takıp çıkaralım.']),
  step(['l6-component','practice','components',7,40,'Component: sorumlulukları ayır','Component, GameObject’e belirli veri veya yetenek ekler. Transform yer, Mesh Filter geometri, Renderer çizim, Collider çarpışma sınırı sorusunu yanıtlar.','Dört Component’i doğru sorumluluk yuvasına bağlar.',['Transform: nerede ve hangi boyutta?','Mesh Filter: hangi geometri?','Mesh Renderer: nasıl görünür?','Collider: nerede temas eder?'],'Her nesnede bulunan Transform’un üç parçasını ayrı ayrı görelim.']),
  step(['l6-transform','teach','axis',7,40,'Transform neden her nesnede var?','Transform; Position, Rotation ve Scale verilerini, ayrıca hiyerarşi ilişkisini taşır. Normal kullanımda GameObject’ten kaldırılmaz.','Yer, yön ve boyut değişimini üç eksenli modelde ayırır.',['Position: nerede?','Rotation: hangi yönde?','Scale: hangi boyutta?','X, Y ve Z yalnız renk değil harfle de tanınır'],'Hazır Cube’un bu bileşenleri nasıl birleştirdiğini inceleyelim.']),
  step(['l6-cube-anatomy','observe','anatomy',7,40,'Bir Cube’un anatomisi','Hazır Cube tek parça sihirli nesne değildir. Transform, Mesh Filter, Mesh Renderer ve Box Collider birlikte görünür ve etkileşebilir bir sonuç üretir.','Katmanlı Cube kesitinde her bileşenin sonucunu tahmin eder.',['Transform uzamsal durumu taşır','Mesh Filter mesh referansını sağlar','Mesh Renderer çizimi yapar','Box Collider temas hacmini tanımlar'],'Şimdi bu temel şekilleri sahneye kendimiz ekleyelim.']),
  step(['l6-create','practice','create',8,50,'İlk primitive nesneleri oluştur','Plane, Cube ve Capsule hızlı prototipleme için hazır temel şekillerdir. Her oluşturma Hierarchy, Scene ve Inspector’da üç ayrı kanıt bırakır.','Ground, Platform_A ve PlayerMarker nesnelerini oluşturup adlandırır.',['Hierarchy satırı oluşmalı','Scene’de yeni nesne seçili görünmeli','Inspector’da Transform bulunmalı','Aynı isimde nesne varsa anlamlı biçimde yeniden adlandırılmalı'],'İlk platformu Position ile hedef konuma taşıyalım.']),
  step(['l6-position','practice','gizmo',8,50,'Position ile taşı','Scene gizmosu ile Inspector sayı alanları aynı Transform Position verisini değiştirir. X=2, Y=0.5, Z=0 platformu zeminin üstüne yerleştirir.','Gizmo ve sayısal alanı senkron kullanarak hedef konuma ulaşır.',['Tek eksen tutamacı diğer eksenleri korur','Yükseklik nesne boyutuyla birlikte düşünülür','Aşırı değer nesneyi görüşten çıkarabilir','Sıfırla işlemi güvenli başlangıca döndürür'],'Konum doğru; şimdi nesnenin baktığı yönü değiştirelim.']),
  step(['l6-rotation','practice','rotation',8,50,'Rotation ile yön ver','Rotation nesnenin yerini değil yönelimini değiştirir. Editor derece alanları gösterir; bu derste quaternion matematiğine girilmez.','Dairesel gizmo ve derece kontrolleriyle rampayı hedef açıya getirir.',['0° başlangıç yönüdür','45° eğimli rampa örneğidir','90° çeyrek dönüştür','Snap modu 15° adımlarla ilerler'],'Yönü ayarladın; şimdi nesnenin gerçek boyutunu değiştir.']),
  step(['l6-scale','practice','scale',7,40,'Scale ile boyutlandır','Scale eksen başına göreli boyuttur. Scene kamerasıyla yaklaşmak nesnenin Scale değerini değiştirmez. Sıfır ve negatif değerler başlangıçta risklidir.','Referans grid üzerinde uniform ve eksen bazlı Scale’i karşılaştırır.',['X genişliği etkiler','Y yüksekliği etkiler','Z derinliği etkiler','Pozitif ve anlamlı başlangıç değerleri kullan'],'Şimdi sahnedeki günlük nesne işlemlerini birlikte uygula.']),
  step(['l6-object-ops','practice','hierarchy',6,35,'Seç, adlandır, çoğalt, etkinleştir','Seçim, yeniden adlandırma, duplicate ve active state; Hierarchy, Scene ve Inspector’da aynı nesne durumunu birlikte günceller.','Platform_A’yı çoğaltıp iki anlamlı platforma dönüştürür.',['Platform_Left adını ver','Duplicate yeni ve kararlı kimlik üretir','Platform_Right adını ver','Disable silme değildir; tekrar etkinleştirilebilir'],'İki platformu ortak bir üst nesne altında gruplayalım.']),
  step(['l6-parent-child','simulate','parent',7,45,'Parent–child ile grup davranışı','Parent–child yalnız görsel klasörleme değildir; child Transform’u parent hareketini izler. World sahneye, local parent’a göre konumu anlatır.','Parent hareketinin iki child üzerindeki sonucunu iki görünümde tahmin eder.',['Environment parent olabilir','İki platform child olur','Parent taşınınca ikisi birlikte hareket eder','Bir child tek başına taşınınca kardeşi hareket etmez'],'Sahneyi kaydedip görünmeyen nesneyi kanıtla teşhis edelim.']),
  step(['l6-save-debug','debug','evidence',7,50,'Kaydet ve görünmeyeni teşhis et','Sahneyi `Assets/Scenes/FirstBlockout.unity` olarak kaydet; sonra görünmeyen nesnede sahne, Hierarchy, active, focus, Transform, Renderer ve kamera kanıtlarını sırayla kontrol et.','İlk başarısız kanıtı bulup en küçük düzeltmeyi uygular.',['Doğru sahne açık mı?','Nesne Hierarchy’de var mı ve etkin mi?','Position ve Scale mantıklı mı?','Renderer açık mı?','Game sorunuysa kamera kadrajında mı?'],'Bütün becerileri tek sahne görevinde birleştir.']),
  step(['l6-game','game','mission',7,45,'Sahne Montaj Atölyesi','Ground, iki platform, bir rampa ve PlayerMarker üret; Transform hedeflerini gir, parent ilişkisini kur, bir nesneyi geçici kapat ve sahneyi kaydet.','Ortak state kullanan Hierarchy–Scene–Inspector laboratuvarını tamamlar.',['Beş nesneyi oluştur','Dört Transform hedefini doğrula','Environment parent ilişkisini kur','Sahne kaydını kanıtla'],'Finalde sahne kurma ve tanı becerilerini yeni hedefe aktar.']),
  step(['l6-finale','finale','finale',10,180,'Etkinlik Bombası','On iki turda GameObject, Component, Transform, primitive, nesne işlemleri, hiyerarşi, debug ve sahne kaydını uygula.','Sahne kurma hedeflerinde en az yüzde 70 ilk deneme başarısı gösterir.',['İlk on tur tek beceri ölçer','Son iki tur çok adımlı boss görevidir','Yüzde 85 ve üzeri ustalık düzeyidir'],'Sahne Kurucusu rozeti açıldı; kodla davranış eklemeye hazırsın.']),
];

export const foundationLessons: Lesson[] = [
  { id:'lesson-004-create-first-project',order:4,module:1,duration:96,status:'published',fileName:'',starterCode:'',title:text('İlk Projeyi Doğru Şablonla Oluşturmak'),summary:text('Sabit Editor sürümü, doğru şablon, anlaşılır ad ve güvenli konumla doğrulanmış ilk Unity projesini oluşturacaksın.'),taskTitle:text('Tutarlı proje manifesti üret.'),taskBody:text('Sürüm, template, pipeline, ad, location ve cloud kararlarını doğrula.'),successMessage:text('Tekrar açılabilir ve kanıtlanmış ilk projen hazır.'),concepts:['template','sample','URP','sürüm','location','import'],steps:lesson4Steps,badge:{tr:{name:'İlk Temel',description:'Doğru sürüm, şablon ve konumla ilk projeyi oluşturdun.'},en:{name:'İlk Temel',description:'Doğru sürüm, şablon ve konumla ilk projeyi oluşturdun.'}} },
  { id:'lesson-005-editor-map',order:5,module:1,duration:104,status:'published',fileName:'',starterCode:'',title:text('Unity Editor Haritası: Scene, Game, Hierarchy, Inspector, Project ve Console'),summary:text('Unity Editor’de kaybolmadan altı ana panelin görevini, veri ilişkisini ve temel navigasyon hareketlerini öğreneceksin.'),taskTitle:text('Doğru göreve doğru panelden başla.'),taskBody:text('Altı paneli, navigasyonu, Play Mode’u, filtreleri ve layout kurtarmayı uygula.'),successMessage:text('Editor çalışma alanında doğru kanıtı nerede arayacağını biliyorsun.'),concepts:['Scene','Game','Hierarchy','Inspector','Project','Console'],steps:lesson5Steps,badge:{tr:{name:'Editor Rehberi',description:'Altı ana paneli doğru görevle kullandın.'},en:{name:'Editor Rehberi',description:'Altı ana paneli doğru görevle kullandın.'}} },
  { id:'lesson-006-gameobject-component-transform',order:6,module:1,duration:101,status:'published',fileName:'',starterCode:'',title:text('GameObject, Component ve Transform ile Kodsuz İlk Sahne'),summary:text('Tek satır kod yazmadan GameObject–Component mantığını öğrenip Transform ile kaydedilmiş ilk sahne taslağını kuracaksın.'),taskTitle:text('Kodsuz ilk sahneni kur.'),taskBody:text('Primitive nesneler, Transform, nesne işlemleri ve parent ilişkisiyle FirstBlockout sahnesini üret.'),successMessage:text('Sahnedeki varlıkları bileşenleri ve Transform kanıtlarıyla yönetebiliyorsun.'),concepts:['GameObject','Component','Transform','Position','Rotation','Scale'],steps:lesson6Steps,badge:{tr:{name:'Sahne Kurucusu',description:'GameObject, Component ve Transform ile ilk sahneni kurdun.'},en:{name:'Sahne Kurucusu',description:'GameObject, Component ve Transform ile ilk sahneni kurdun.'}} },
];
