import { useMemo, useState } from 'react';
import type { Locale } from '../domain/models';
import type { LessonStep } from '../learning/course';
import { localize } from '../learning/course';
import { Icon } from '../shared/Icon';
import { hasSignatureExperience, SignatureExperience } from './SignatureExperience';

type Challenge = {
  prompt: string;
  options: string[];
  answer: number;
  explanation: string;
  hint: string;
};

const challenges: Record<string, Challenge> = {
  'l1-welcome': { prompt:'Bir karakterin nasıl davranacağını anlamadan doğrudan kod satırlarına geçersek ne eksik kalır?', options:['Kodun hangi davranışı anlattığını kavramak zorlaşır','Kod öğrenmeye artık gerek kalmaz','Unity kod kullanmadan bütün oyunu kendisi hazırlar'], answer:0, explanation:'Kod, tasarladığımız davranışı bilgisayara anlatır. Davranışın parçalarını tanımadan yalnızca satırları ezberlemek, o satırların neden yazıldığını görmemizi zorlaştırır.', hint:'Bir tarifteki kelimeleri ezberlemekle yemeğin nasıl oluştuğunu anlamak aynı şey değildir.' },
  'l1-observe': { prompt:'Karakterin kalan enerjisi hangi görevdedir?', options:['Input','Durum','Output'], answer:1, explanation:'Enerji, oyunun o anda sakladığı ve kuralların okuyabildiği bir durum bilgisidir.', hint:'Oyunun hatırladığı bilgiyi ara.' },
  'l1-four-link': { prompt:'Doğru sistem sırası hangisidir?', options:['Output → durum → kural → input','Input → kural → durum → output','Kural → input → output → durum'], answer:1, explanation:'Oyuncu niyet gönderir, kural mevcut durumu değerlendirir, durum güncellenir ve sonuç gösterilir.', hint:'Sonuç, karar verilmeden önce oluşamaz.' },
  'l1-input': { prompt:'Gamepad A ve ekrana dokunma aynı “Zıpla” eylemine bağlanırsa ortak olan nedir?', options:['Fiziksel cihaz','Oyundaki niyet','Karakterin konumu'], answer:1, explanation:'Cihazlar farklı sinyal üretse de oyunda aynı niyeti temsil edebilir.', hint:'Tuşun şekline değil, oyunda ne istendiğine bak.' },
  'l1-rule': { prompt:'Zıpla girdisi geldi; karakter havada. Yer tabanlı kural ne yapmalı?', options:['Her durumda yeniden zıplatmalı','Mevcut durumu kontrol edip isteği reddetmeli','Input’u durum olarak saklamalı'], answer:1, explanation:'Kural hem isteği hem mevcut durumu değerlendirir. Input her zaman değişim üretmez.', hint:'Karar için yalnız isteğin gelmesi yeterli mi?' },
  'l1-state': { prompt:'Karakter anahtarı aldığında hangi bilgi doğrudan değişir?', options:['anahtarVar','kapıAçık','oyunun build türü'], answer:0, explanation:'Anahtarı alma olayı `anahtarVar` bilgisini değiştirir; kapı ancak ayrı bir kural çalışınca açılır.', hint:'Olayın doğrudan etkilediği değeri seç.' },
  'l1-output': { prompt:'Kilitli kapıda yalnız kısa bir ses kullanmanın riski nedir?', options:['Ses her zaman çok yavaştır','Sesi duyamayan oyuncu bilgiyi kaçırabilir','Output yalnız metin olabilir'], answer:1, explanation:'Önemli bilgi mümkünse görsel/metinsel ikinci bir kanalla da iletilmelidir.', hint:'Bilginin tek kanala bağlı kalmasını düşün.' },
  'l1-precision': { prompt:'“Karakteri biraz ilerlet” komutunda hangi bilgi eksiktir?', options:['Yön ve miktar','Dosya uzantısı','Editor lisansı'], answer:0, explanation:'Uygulanabilir komut hedefi, yönü, miktarı ve gerekirse durma koşulunu açıklar.', hint:'Bilgisayar “biraz” kelimesini nasıl ölçecek?' },
  'l1-roles': { prompt:'Oyuncuya çalıştırması için hangi sonuç teslim edilir?', options:['Editor yerleşimi','Build','Kod editörünün ayar ekranı'], answer:1, explanation:'Build, proje kaynaklarından üretilen ve oyuncunun çalıştırdığı pakettir.', hint:'Üretim masası ile teslim edilen ürünü ayır.' },
  'l1-loop': { prompt:'Bir sonraki oyun turu hangi bilgiyle başlar?', options:['Her zaman sıfır durumla','Önceki turun bıraktığı güncel durumla','Yalnız son ses efektiyle'], answer:1, explanation:'Durum süreklilik taşır; yeni input önceki turun bıraktığı bilgi üzerinde değerlendirilir.', hint:'Karakterin konumu her tur başında sıfırlanır mı?' },
  'l1-debug': { prompt:'Input geldi, anahtarVar=true; kapı kuralı false bekliyor. İlk yanlış nokta neresi?', options:['Input','Kural','Kapı görseli'], answer:1, explanation:'İlk iki kanıt doğru; ters değeri kontrol eden kural ilk beklenmeyen noktadır.', hint:'Kanıtları soldan sağa izle.' },
  'l1-lab': { prompt:'Yakıt sıfırken hızlanma girdisine doğru sistem cevabı hangisidir?', options:['Hızı artır ve yakıtı eksiye düşür','Durumu koru ve anlaşılır uyarı ver','Input’u yok sayıp hiçbir geri bildirim verme'], answer:1, explanation:'Kural isteği reddeder, durumu güvenli tutar ve output oyuncuya nedenini anlatır.', hint:'Hem güvenli durum hem anlaşılır output gerekli.' },
  'l1-game': { prompt:'Bir kapsülü göndermeden önce hangi kanıt çifti gerekir?', options:['Yakıt yeterli ve kapı açık','Müzik açık ve Editor kurulu','Klasör adı kısa ve ses yüksek'], answer:0, explanation:'Gönderim kuralı ilgili mevcut durumları doğrulamalıdır.', hint:'Gönderimin güvenliğini doğrudan etkileyen durumları seç.' },
  'l2-recall': { prompt:'Bilgisayar kapandığında proje bilgisinin kalmasını sağlayan temel yapı nedir?', options:['Geçici oyun durumu','Diskteki dosya','Ekrandaki animasyon'], answer:1, explanation:'Dosya, bilgiyi kalıcı saklama ortamında tutar.', hint:'Elektrik kesilse de hangi şey kalır?' },
  'l2-file-folder': { prompt:'`Scripts/` öğesinin temel görevi nedir?', options:['Tek bir C# komutu çalıştırmak','Dosya ve alt klasörleri düzenlemek','Build olmak'], answer:1, explanation:'Scripts bir klasördür; içindeki dosyaları düzenler.', hint:'İçeriği mi taşır, öğeleri mi düzenler?' },
  'l2-name-extension': { prompt:'`PlayerMove.cs.txt` dosyasında gerçek son uzantı nedir?', options:['.cs','.txt','.cs.txt her zaman tek uzantıdır'], answer:1, explanation:'Son noktanın ardından gelen bölüm gerçek son uzantıdır; gizli uzantılar yanıltabilir.', hint:'En sağdaki son noktadan sonrasını oku.' },
  'l2-path': { prompt:'Aynı adlı iki dosya nasıl birbirinden ayrılır?', options:['Yalnız simge rengiyle','Tam yollarıyla','Dosya adı her zaman benzersizdir'], answer:1, explanation:'Dosyanın konumu, kökten dosyaya kadar tam yoluyla belirlenir.', hint:'Adres benzetmesini kullan.' },
  'l2-root': { prompt:'Paket bağımlılıkları hangi temel proje parçasıyla ilişkilidir?', options:['Packages','Assets/Scripts','Ekran görüntüsü klasörü'], answer:0, explanation:'Packages, projenin paket bağımlılıklarını tanımlar.', hint:'İçerik değil bağımlılık kaydını ara.' },
  'l2-assets-boundary': { prompt:'Hub’da Open project için hangi klasör seçilir?', options:['MyGame/','MyGame/Assets/','MyGame/Assets/Scripts/'], answer:0, explanation:'Proje kökü Assets, Packages ve ProjectSettings öğelerini birlikte taşır.', hint:'Üç temel öğenin ortak ebeveynini seç.' },
  'l2-zip': { prompt:'ZIP içindeki projede çalışmadan önce doğru adım nedir?', options:['Yalnız Assets’i masaüstüne sürüklemek','Arşivin tamamını güvenli klasöre çıkartmak','ZIP adını .unity yapmak'], answer:1, explanation:'Proje bütünlüğü için arşiv tamamen çıkartılır ve kök yeniden doğrulanır.', hint:'Tek bir parça eksiksiz proje değildir.' },
  'l2-safe-location': { prompt:'Başlangıç projesi için en güçlü aday hangisidir?', options:['Sistem klasörü/Windows/','Downloads/Yeni Klasör (27)/','D:/GameDev/Projects/FirstGame/'], answer:2, explanation:'Kısa, anlamlı ve kontrol edilen bir çalışma yolu izin ve düzen riskini azaltır.', hint:'İzin, açıklık ve yol uzunluğunu birlikte düşün.' },
  'l2-naming': { prompt:'Hangi ad proje kimliğini en açık taşır?', options:['final_son_son2','Yeni Klasör','LevelUpPractice'], answer:2, explanation:'Anlamlı tam kelimeler sürüm karmaşasını ve belirsizliği azaltır.', hint:'Altı ay sonra hangi adı anlayabilirsin?' },
  'l2-backup': { prompt:'Aynı diskteki iki proje kopyası hangi riske karşı yetersizdir?', options:['Disk arızası','Dosya adını unutmak','Editor temasının değişmesi'], answer:0, explanation:'Tek disk bozulursa iki klasör de birlikte kaybedilebilir.', hint:'İki kopya aynı fiziksel riski paylaşıyor mu?' },
  'l2-diagnose': { prompt:'Hub yolu `Game.zip/Game/Assets` ise ilk kök sorun nedir?', options:['Projenin arşiv içinde ve Assets seviyesinde seçilmesi','Proje adının İngilizce olması','Assets klasörünün bulunması'], answer:0, explanation:'Önce arşiv çıkartılmalı, sonra Assets’in üstündeki proje kökü seçilmelidir.', hint:'İki ayrı sınır hatası var: arşiv ve kök.' },
  'l2-lab': { prompt:'Bağımsız yedek için doğru aday hangisidir?', options:['GameDev/Projects/LevelUpPractice/','Başka ortam/Backups/LevelUpPractice_2026-09-16.zip','LevelUpPractice/Assets/Backup/'], answer:1, explanation:'Yedek çalışma projesinden ve mümkünse aynı risk alanından ayrılır.', hint:'Çalışma kopyasının içinde olan şey bağımsız mı?' },
  'l2-game': { prompt:'Kurtarma görevinde ilk hareket ne olmalıdır?', options:['Rastgele klasör silmek','Haritayı ve mevcut kanıtları incelemek','Bütün dosyaların adını değiştirmek'], answer:1, explanation:'Güvenli teşhis, değişiklikten önce mevcut durumu kanıtla okur.', hint:'Önce ölç, sonra değiştir.' },
  'l3-recall': { prompt:'Oyuncuya hangisi gönderilir?', options:['Unity Hub','Build','Assets klasörü tek başına'], answer:1, explanation:'Build, oyuncunun çalıştırdığı dağıtılabilir sonuçtur.', hint:'Yönetim aracı ile ürün sonucunu ayır.' },
  'l3-toolchain': { prompt:'Platforma özel build desteğini hangi parça sağlar?', options:['Modül','Proje adı','Lisans avatarı'], answer:0, explanation:'Modüller Android, Web veya belirli masaüstü hedefleri için ek araç zinciri sağlar.', hint:'Hedef platform için eklenen parçayı ara.' },
  'l3-preflight': { prompt:'Kurulum boyutu için en güvenilir bilgi hangisidir?', options:['Ezberlenmiş sabit bir sayı','Seçilen Editor ve modüller için Hub’ın gösterdiği güncel boyut','Başka öğrencinin geçen yılki tahmini'], answer:1, explanation:'Sürüm ve modül seçimi boyutu değiştirir; güncel kurulum ekranı esas alınır.', hint:'Hangi bilgi seçiminle birlikte güncellenir?' },
  'l3-source': { prompt:'Kurucuyu seçerken hangi ikili birlikte doğrulanır?', options:['Logo rengi ve dosya boyutu','Resmî alan adı ve işletim sistemi','Reklam sayısı ve indirme hızı'], answer:1, explanation:'Kaynağın resmî oluşu ve paketin işletim sistemine uygunluğu iki ayrı kanıttır.', hint:'Kaynak ve hedef cihaz.' },
  'l3-hub': { prompt:'Hub açıldı; Installations boş. Bu neyi gösterir?', options:['Editor henüz kurulmamış olabilir','Editor kesin kuruldu','İlk oyun otomatik oluştu'], answer:0, explanation:'Hub yöneticidir; Editor kurulumu ayrıca Installations alanında görünmelidir.', hint:'Hub ile Editor aynı şey değil.' },
  'l3-account-license': { prompt:'Oturum açmış olmak ile etkin lisans aynı kanıt mıdır?', options:['Evet, her durumda aynıdır','Hayır, kimlik ve kullanım hakkı ayrı durumlardır','Yalnız dosya uzantısı farklıdır'], answer:1, explanation:'Hesap kimliği ile lisans durumu ayrı kontrol edilir.', hint:'Giriş kartı ve kullanım yetkisi benzetmesini düşün.' },
  'l3-version': { prompt:'Kurs belirli patch sürümüne sabitliyse daha yeni sürüm görünce ne yapılır?', options:['Otomatik yükseltilir','Kurs sürümü korunur; uyumluluk ayrı test edilir','Bütün projeler silinir'], answer:1, explanation:'Yeni sürüm, paket ve proje uyumu doğrulanmadan eğitim tabanı değiştirilmez.', hint:'En yeni olmak ile uyumlu olmak aynı şey mi?' },
  'l3-modules': { prompt:'Yalnız Windows masaüstünde öğrenen öğrenci ne yapmalı?', options:['Bütün platform modüllerini seçmeli','Hedef için gereken en küçük seti seçmeli','Editor kurmamalı'], answer:1, explanation:'Gereksiz modül disk, indirme ve bakım maliyeti üretir; sonradan eklenebilir.', hint:'Hedef ve maliyeti birlikte düşün.' },
  'l3-install': { prompt:'Bir modül “failed” durumundaysa en güvenli ilk yaklaşım nedir?', options:['Proje klasörünü silmek','Hata bilgisini kaydedip disk/ağı doğrulamak','Bilgisayarı zorla kapatmak'], answer:1, explanation:'Belirti kaydedilir, ilgili kaynaklar kontrol edilir ve yalnız başarısız parça yeniden denenir.', hint:'En küçük güvenli düzeltme.' },
  'l3-ide': { prompt:'IDE’nin temel görevi hangisidir?', options:['Sahne ışıklarını çizmek','Kodu düzenlemek, analiz etmek ve debug etmek','Unity lisansı vermek'], answer:1, explanation:'IDE kod çalışma ortamıdır; Unity Editor sahne ve oyun çalışmasını yönetir.', hint:'Yazı masası ile atölyeyi ayır.' },
  'l3-verify': { prompt:'Hangisi kurulumun ölçülebilir kanıtıdır?', options:['“Sanırım tamamlandı” demek','Seçilen Editor sürümünün Installed görünmesi','Masaüstünde rastgele bir kısayol görmek'], answer:1, explanation:'Sürümün Installations alanında açıkça görünmesi doğrulanabilir kanıttır.', hint:'Başka biri aynı sonucu gözleyebilir mi?' },
  'l3-debug': { prompt:'Script dosyası açılıyor ama Unity türleri tanınmıyor. İlk ilgili katman hangisidir?', options:['IDE entegrasyonu/proje dosyaları','Ses mikseri','Proje yedeğinin tarihi'], answer:0, explanation:'Belirti kod editörü bağlantısı ve Unity proje entegrasyonuyla ilgilidir.', hint:'Sorunun görüldüğü en yakın aracı seç.' },
  'l3-game': { prompt:'25 GB bütçede kullanılmayacak üç platform modülünü seçmek ne üretir?', options:['Daha iyi kod bilgisi','Gereksiz indirme ve disk maliyeti','Otomatik mağaza yayını'], answer:1, explanation:'Modül seçimi hedefe dayanır; fazlalık kurulum maliyeti üretir.', hint:'Her ek parça ücretsiz kaynak mı kullanır?' },
  'l4-recall': { prompt:'Unity Hub’da yeni proje oluştururken önce hangi üç kararı doğrularsın?', options:['Sürüm, proje kökü ve Editor','Ses, skor ve kamera','Build, oyuncu adı ve renk'], answer:0, explanation:'Proje oluşturma kararı doğru Editor sürümü ve güvenli proje kökü üzerine kurulur.', hint:'Ders 2 ve 3’ten gelen iki temel kanıtı düşün.' },
  'l4-template': { prompt:'Template’in sağlamadığı öğe hangisidir?', options:['Başlangıç paketleri','Özgün ve bitmiş oyun mekaniğin','Başlangıç ayarları'], answer:1, explanation:'Template başlangıç yapısıdır; özgün oyun içeriğini öğrenci üretir.', hint:'Boş daire planı, içinde yaşayacak hikâyeyi hazır verir mi?' },
  'l4-pipeline': { prompt:'Kursun mobil ve orta seviye PC odaklı 3D başlangıcı için tercih nedir?', options:['URP','HDRP her durumda','Pipeline seçmemek'], answer:0, explanation:'URP, bu kursun dengeli ve sabitlenmiş başlangıç yoludur.', hint:'Universal sözcüğünün hedeflediği geniş cihaz aralığını düşün.' },
  'l4-version': { prompt:'Kurs 6000.6.x patch hattına sabitliyse doğru yaklaşım?', options:['Rastgele latest seçmek','Kursun belirlediği tam sürümü seçmek','Her açılışta yükseltmek'], answer:1, explanation:'Tam sürüm; ekran, paket ve ekip uyumunu korur.', hint:'En yeni olmak ile aynı ortamda olmak aynı şey değildir.' },
  'l4-name': { prompt:'En anlaşılır proje adı hangisidir?', options:['oyunfinalson3','LevelUpPractice','Yeni Klasör (19)'], answer:1, explanation:'Kısa ve niyeti anlatan tam kelimeler ileride de okunur.', hint:'Altı ay sonra klasörü gördüğünü düşün.' },
  'l4-location': { prompt:'Name `LevelUpPractice`, Location `D:/GameDev/Projects` ise kök nerede oluşur?', options:['D:/GameDev/Projects/LevelUpPractice','D:/GameDev/Projects/Assets','ZIP/LevelUpPractice'], answer:0, explanation:'Location üst klasördür; proje adı onun altında yeni kökü üretir.', hint:'Arsa ile bina adını birleştir.' },
  'l4-cloud': { prompt:'Yerel Unity projesi için bütün cloud hizmetleri zorunlu mu?', options:['Evet','Hayır, ihtiyaca bağlıdır','Yalnız proje adı uzunsa'], answer:1, explanation:'Yerel proje oluşturma ile cloud bağlantısı ayrı kararlardır.', hint:'Dosyanın diskte yaşaması için ek çevrim içi servis şart mı?' },
  'l4-summary': { prompt:'Hangi manifest satırı doğrudan risklidir?', options:['URP + course version','Location: BaşkaOyun/Assets','Cloud: kapalı'], answer:1, explanation:'Başka projenin Assets klasörü içine yeni proje kurmak iç içe kök üretir.', hint:'İki proje sınırının birbirine girdiği satırı ara.' },
  'l4-create': { prompt:'Create düğmesine basmadan önce hangi sonuç görünür olmalı?', options:['Sürüm–template–ad–konum manifesti','Oyunun final skoru','C# stack trace'], answer:0, explanation:'Oluşturma öncesi kararlar tek özette tutarlı görünmelidir.', hint:'Henüz proje yok; önce hangi karar paketi var?' },
  'l4-first-open': { prompt:'İlk açılışta import ne yapar?', options:['Dosyaları otomatik buluta yollar','Asset’leri Unity’nin kullanacağı biçime hazırlar','Projeyi build eder'], answer:1, explanation:'Import kaynak asset verisini Editor’ün kullanacağı yerel biçime hazırlar.', hint:'“İçe aktarma” ile “internete yükleme” aynı işlem değildir.' },
  'l4-verify': { prompt:'Doğru proje kökünü en iyi hangi kanıt destekler?', options:['Project’te Assets ve doğru proje yolunun birlikte görünmesi','Masaüstü duvar kâğıdı','Hub avatarı'], answer:0, explanation:'Yol ve Project penceresi aynı proje kimliğini bağımsız biçimde doğrular.', hint:'Başka birinin de gözleyebileceği proje kanıtını seç.' },
  'l4-debug': { prompt:'Hub’da `MyGame/Assets` proje diye açılmış. En küçük güvenli düzeltme?', options:['Assets içeriğini silmek','Assets’in üstündeki proje kökünü seçmek','Yeni işletim sistemi kurmak'], answer:1, explanation:'Kök; Assets, Packages ve ProjectSettings’in ortak ebeveynidir.', hint:'Dosyaları değiştirmek yerine yanlış seçilen sınırı düzelt.' },
  'l4-game': { prompt:'Proje fırlatılmadan önce hangi ışıkların birlikte yeşil olması gerekir?', options:['Sürüm, template, ad ve konum','Müzik, skor ve can','Kamera, zıplama ve ses'], answer:0, explanation:'Fırlatma manifesti proje oluşturma kararlarının tutarlılığını ölçer.', hint:'Henüz oyun mekaniği değil, proje kabuğu kuruluyor.' },
  'l5-recall': { prompt:'Engelleyici açılış hatasını hangi panel kanıtlar?', options:['Console','Game','Hierarchy'], answer:0, explanation:'Console log, warning ve error kayıtlarını gösterir.', hint:'Mesaj ve hata merkezini düşün.' },
  'l5-map': { prompt:'Seçili nesnenin özelliklerini hangi panel gösterir?', options:['Inspector','Project','Game'], answer:0, explanation:'Inspector seçili öğenin düzenlenebilir ayrıntı yüzeyidir.', hint:'Bir şeyi seçtikten sonra ayrıntısına nerede bakarsın?' },
  'l5-scene-game': { prompt:'Scene görünümünde orbit yapmak neyi değiştirir?', options:['Geliştiricinin gözlem bakışını','Game kamerasının Transform’unu otomatik olarak','Nesnenin Scale değerini'], answer:0, explanation:'Scene kamerası düzenleme bakışıdır; oyun kamerası ve nesne verisi değişmez.', hint:'Gözlemcinin yeri mi, sahnedeki nesne mi değişiyor?' },
  'l5-hierarchy': { prompt:'Hierarchy temel olarak neyi listeler?', options:['Açık sahnedeki GameObject’leri','Bilgisayardaki bütün dosyaları','Yalnız Console hatalarını'], answer:0, explanation:'Hierarchy açık sahnelerin nesne hiyerarşisidir.', hint:'Dosya tarayıcısıyla sahne listesini ayır.' },
  'l5-project': { prompt:'`Rock` asset’i ile sahnedeki üç Rock arasındaki ilişki?', options:['Bir asset birden fazla sahne instance’ı üretebilir','Her sahne nesnesi ayrı işletim sistemidir','Project yalnız ışıkları gösterir'], answer:0, explanation:'Project asset’i saklar; Hierarchy sahnedeki örnekleri gösterir.', hint:'Kalıp ile ondan üretilen örnekleri düşün.' },
  'l5-inspector': { prompt:'Light yerine Material seçilince Inspector neden değişir?', options:['Seçili öğenin türüne ve özelliklerine uyum sağladığı için','Panel bozulduğu için','Play Mode başladığı için'], answer:0, explanation:'Inspector sabit içerik değil, seçimin düzenleme yüzeyidir.', hint:'Ayrıntı paneli hangi öğenin ayrıntısını gösteriyor?' },
  'l5-navigation': { prompt:'Seçili nesneyi Scene görünümünde merkeze almak hangi harekettir?', options:['Focus','Scale','Clear'], answer:0, explanation:'Focus Scene kamerasını seçili hedefe taşır; nesne verisini değiştirmez.', hint:'Hedefi kaybettiğinde görünümü ona getirirsin.' },
  'l5-toolbar-play': { prompt:'Play Mode sırasında yapılan geçici bir değişikliğin riski?', options:['Durdurunca geri dönebilir','Her zaman build olur','Project penceresini siler'], answer:0, explanation:'Runtime denemeleri kalıcı düzenleme ile karıştırılmamalıdır.', hint:'Çalıştırma ile düzenleme durumlarını ayır.' },
  'l5-console': { prompt:'Console’daki Clear düğmesi ne yapmaz?', options:['Kök nedeni düzeltmez','Görünen mesaj listesini temizler','Yeni mesajların gelmesine izin verir'], answer:0, explanation:'Clear yalnız kayıt görünümünü temizler; hatalı kod veya ayar aynı kalır.', hint:'Belirtiyi silmek, nedeni gidermek midir?' },
  'l5-search': { prompt:'Arama sonucu sıfırsa ilk çıkarım ne olmalı?', options:['Öğe kesin silindi','Filtre eşleşmemiş olabilir','Proje kesin bozuldu'], answer:1, explanation:'Filtre görünürlüğü sınırlar; öğeyi dosyadan veya sahneden silmez.', hint:'Arama kutusunu temizleyince ne olur?' },
  'l5-layout': { prompt:'Panel kapanınca en güvenli ilk çözüm?', options:['Window/Layout üzerinden geri getirmek','Projeyi silmek','Editor’ü yeniden kurmak'], answer:0, explanation:'Panel yerleşimi geri alınabilir arayüz durumudur.', hint:'İçerik değil, çalışma alanı görünümü değişti.' },
  'l5-debug': { prompt:'Bir Material asset’ini bulma görevi hangi panelden başlar?', options:['Project','Hierarchy','Game'], answer:0, explanation:'Asset dosyaları Project penceresinde bulunur.', hint:'Sahne instance’ı değil kaynak varlık aranıyor.' },
  'l5-game': { prompt:'Oyuncunun kamera çıktısını kontrol etmek için hangi panel açılır?', options:['Game','Inspector','Project'], answer:0, explanation:'Game görünümü etkin kameranın oyuncuya sunduğu çıktıdır.', hint:'Geliştirici bakışı değil oyuncu bakışı.' },
  'l6-recall': { prompt:'Bir nesnenin Transform değerini değiştirmek için doğru rota?', options:['Hierarchy’de seç → Inspector’da değiştir → Scene’de doğrula','Project’i sil → Console’u temizle','Game’de zoom → build al'], answer:0, explanation:'Seçim, düzenleme ve görsel kanıt üç panelde ardışık ilerler.', hint:'Önce kimi değiştirdiğini seçmelisin.' },
  'l6-gameobject': { prompt:'Mesh Renderer kapatılırsa ne olur?', options:['GameObject kalır, çizimi görünmez olabilir','GameObject kesin silinir','Transform başka projeye taşınır'], answer:0, explanation:'Renderer görünürlüğü sağlar; GameObject kimliği Hierarchy’de kalır.', hint:'Taşıyıcı ile ona takılan yeteneği ayır.' },
  'l6-component': { prompt:'Küpün çarpışma sınırını hangi Component taşır?', options:['Box Collider','Mesh Renderer','Transform'], answer:0, explanation:'Collider fiziksel temas sınırını tanımlar; görünürlüğü Renderer sağlar.', hint:'Tel-kafes temas hacmini düşün.' },
  'l6-transform': { prompt:'Nesnenin yönünü hangi Transform grubu değiştirir?', options:['Rotation','Position','Scale'], answer:0, explanation:'Rotation yönelimi, Position konumu, Scale boyutu değiştirir.', hint:'Döndürmek ile taşımayı ayır.' },
  'l6-cube-anatomy': { prompt:'Mesh bilgisini tutan fakat tek başına çizmeyen parça?', options:['Mesh Filter','Mesh Renderer','Box Collider'], answer:0, explanation:'Mesh Filter geometri referansını sağlar; Renderer onu çizer.', hint:'“Hangi şekil?” ile “çiz” görevlerini ayır.' },
  'l6-create': { prompt:'Yeni Cube oluşturulduğunu hangi üçlü kanıtlar?', options:['Hierarchy satırı, Scene seçimi, Inspector Transform','Console rengi, build adı, müzik','Hub avatarı, ZIP, lisans'], answer:0, explanation:'Aynı nesne Editor’ün üç bağlı yüzeyinde iz bırakır.', hint:'Liste, görünüm ve özellik panelini birlikte düşün.' },
  'l6-position': { prompt:'Gizmo ile X ekseninde taşıyınca Inspector’da ne değişmelidir?', options:['Position X','Rotation X','Scale X'], answer:0, explanation:'Gizmo ve Inspector aynı Transform Position state’ini düzenler.', hint:'İşlem taşıma mı, döndürme mi?' },
  'l6-rotation': { prompt:'Rampayı 45° eğmek hangi veriyi değiştirir?', options:['Rotation','Position','Active state'], answer:0, explanation:'Eğim nesnenin yönelimidir; konumu veya varlığı değildir.', hint:'Nesne aynı yerde kalıp yön değiştirebilir.' },
  'l6-scale': { prompt:'Scene kamerasıyla yaklaşınca nesnenin Scale değeri?', options:['Değişmez','Mutlaka iki kat olur','Sıfıra iner'], answer:0, explanation:'Zoom gözlem bakışını, Scale nesnenin verisini değiştirir.', hint:'Kameranın yaklaşması ile nesnenin büyümesini ayır.' },
  'l6-object-ops': { prompt:'Bir nesneyi disable etmek ne demektir?', options:['Geçici olarak devre dışı bırakmak','Dosyadan kalıcı silmek','Parent yapmak'], answer:0, explanation:'Active state kapanır; nesne Hierarchy’de kalır ve yeniden açılabilir.', hint:'Satır hâlâ listede görünüyor mu?' },
  'l6-parent-child': { prompt:'Parent hareket edince child için beklenen?', options:['Parent dönüşümünü izler','Her zaman yerinde kalır','Project’ten silinir'], answer:0, explanation:'Child Transform’u parent hiyerarşisinden etkilenir.', hint:'Bir rafı taşıdığında üzerindeki kutuları düşün.' },
  'l6-save-debug': { prompt:'Nesne görünmüyor; Hierarchy’de var ve active açık. Sıradaki güçlü kanıt?', options:['Focus ile bulup Position/Scale’i kontrol etmek','Projeyi silmek','Her Component’i rastgele kapatmak'], answer:0, explanation:'Kanıt zinciri sırayla ilerler; konum ve ölçek görünürlükte doğrudan etkilidir.', hint:'Nesnenin gerçekten nerede olduğunu ölç.' },
  'l6-game': { prompt:'Sahne Montaj Atölyesi’nin tamamlanma kanıtı?', options:['Nesneler, Transform hedefleri, parent ve scene save birlikte doğru','Yalnız güzel görünmesi','Yalnız bir Cube bulunması'], answer:0, explanation:'Başarı tek görüntü değil, veri yapısı ve kaydetme kanıtlarının bütünüdür.', hint:'Hierarchy, Inspector ve Project kanıtlarını birlikte düşün.' },
};

const kindLabel: Record<LessonStep['kind'], string> = {
  prepare:'GERİ ÇAĞIR', teach:'KAVRAMI KUR', observe:'GÖZLEMLE', practice:'KONTROLLÜ UYGULAMA', simulate:'CANLI SİMÜLASYON', debug:'KANITLA TEŞHİS', lab:'BAĞIMSIZ LABORATUVAR', game:'MİNİ OYUN', test:'SAĞLIK TESTİ', finale:'ETKİNLİK BOMBASI',
};

const experienceByStep: Record<string, string> = {
  'l1-welcome':'story','l1-observe':'trace','l1-four-link':'sequence','l1-input':'connect','l1-rule':'decision','l1-state':'simulator','l1-output':'channels','l1-precision':'instruction','l1-roles':'roles','l1-loop':'loop','l1-debug':'diagnostic','l1-lab':'builder','l1-game':'mission',
  'l2-recall':'bridge','l2-file-folder':'sorter','l2-name-extension':'extension','l2-path':'breadcrumb','l2-root':'project-tree','l2-assets-boundary':'root-picker','l2-zip':'archive','l2-safe-location':'location','l2-naming':'validator','l2-backup':'backup','l2-diagnose':'diagnostic','l2-lab':'builder','l2-game':'mission',
  'l3-recall':'bridge','l3-toolchain':'toolchain','l3-preflight':'checklist','l3-source':'source','l3-hub':'installer','l3-account-license':'identity','l3-version':'version','l3-modules':'modules','l3-install':'process','l3-ide':'ide','l3-verify':'evidence','l3-debug':'clinic','l3-game':'architect',
};

const modeFor = (step: LessonStep) => experienceByStep[step.id] ?? step.activity;

function ExperienceStage({ step, bullets, onReady }: { step: LessonStep; bullets: string[]; onReady: () => void }) {
  const mode = modeFor(step);
  const [visited, setVisited] = useState<Set<number>>(() => new Set());
  const [cursor, setCursor] = useState(0);
  const [toggle, setToggle] = useState(false);
  const [value, setValue] = useState(35);
  const [typed, setTyped] = useState('');
  const [message, setMessage] = useState('Öğrenme yüzeyi hazır.');
  const mark = (index: number, required = bullets.length) => {
    setVisited((current) => {
      const next = new Set(current).add(index);
      if (next.size >= Math.max(1, required)) onReady();
      return next;
    });
  };
  const advance = () => {
    const next = Math.min(cursor + 1, Math.max(0, bullets.length - 1));
    setCursor(next);
    if (next === bullets.length - 1) onReady();
  };
  const completeTyped = () => {
    if (typed.trim().length < 3) { setMessage('Önce anlamlı bir değer yaz.'); return; }
    setMessage('Değer yüzeydeki sonuçla birlikte doğrulandı.');
    onReady();
  };
  const sequenceModes = ['sequence','instruction','breadcrumb','archive','route','process','toolchain','installer','loop'];
  const narrativeModes = ['story','trace','bridge','extension','backup'];
  const choiceModes = ['decision','source','identity','version','toggle','modules'];
  const mapModes = ['hotspot','map'];
  const treeModes = ['tree','project-tree','root-picker','location','hierarchy'];
  const sceneModes = ['navigation','gizmo','axis','rotation','scale','object','create','parent'];

  if (sequenceModes.includes(mode)) return <section className={`experience-stage experience-${mode}`}><header><span>ETKİLEŞİMLİ AKIŞ</span><h3>Bu süreç, bir önceki adımın bıraktığı bilgiyle ilerliyor.</h3><p>Düğümler sırayla açıldığında yalnızca sonucu değil, sonuca götüren bağlantıyı da görebilirsin.</p></header><div className="process-console"><div className="process-rail">{bullets.map((bullet,index)=><button key={bullet} type="button" className={index<cursor?'passed':index===cursor?'active':''} disabled={index>cursor} onClick={()=>{mark(index);setMessage(bullet);if(index===cursor)advance();}}><b>{String(index+1).padStart(2,'0')}</b><span>{bullet}</span><i /></button>)}</div><aside><small>CANLI KANIT</small><strong>{message}</strong><div className="signal-line"><i style={{width:`${((cursor+1)/bullets.length)*100}%`}} /></div><span>{cursor+1} / {bullets.length}</span></aside></div></section>;

  if (narrativeModes.includes(mode)) return <section className={`experience-stage experience-${mode}`}><header><span>GÖRSEL HİKÂYE</span><h3>Görünen sonucun arkasında hangi nedenler var?</h3><p>Her sahne olayın başka bir parçasını gösteriyor. Paneller ilerledikçe parçalar tek bir hikâyede birleşiyor.</p></header><div className="story-deck"><article><small>SAHNE {String(cursor+1).padStart(2,'0')}</small><b>{['INPUT','DOSYA','KANIT','ARAÇ'][cursor%4]}</b><p>{bullets[cursor]}</p><div className="story-visual" aria-hidden="true"><i/><i/><span>{cursor+1}</span></div></article><nav>{bullets.map((bullet,index)=><button key={bullet} className={index===cursor?'active':''} type="button" onClick={()=>{setCursor(index);mark(index);}} aria-label={`${index+1}. sahne`}>{index+1}</button>)}</nav><button className="button button-secondary" type="button" onClick={()=>{mark(cursor);advance();}}>{cursor===bullets.length-1?'Hikâyeyi tamamla':'Sonraki sahne'}<Icon name="arrow-right" /></button></div></section>;

  if (choiceModes.includes(mode)) return <section className={`experience-stage experience-${mode}`}><header><span>KARAR SİMÜLATÖRÜ</span><h3>Her seçimin sistemde bıraktığı iz farklıdır.</h3><p>Soldaki olasılıklar değiştikçe, sağdaki canlı sonuç hangi bilginin etkilendiğini gösteriyor.</p></header><div className="decision-lab"><div>{bullets.map((bullet,index)=><button type="button" key={bullet} className={visited.has(index)?'active':''} onClick={()=>{mark(index);setCursor(index);setToggle(index%2===0);setMessage(bullet);}}><span>{index+1}</span><strong>{bullet}</strong><Icon name="chevron-right" /></button>)}</div><aside className={toggle?'on':''}><small>{mode==='toggle'?'YEREL / CLOUD DURUMU':'SEÇİM SONUCU'}</small><div className="decision-orb"><i/><b>{toggle?'ON':'SET'}</b></div><strong>{message}</strong><p>Karar değiştiğinde manifest ve açıklama birlikte güncellenir.</p></aside></div></section>;

  if (mapModes.includes(mode)) return <section className={`experience-stage experience-${mode}`}><header><span>EDITOR HARİTASI</span><h3>Her panel başka bir sorunun cevabını taşıyor.</h3><p>Bir bölge açıldığında yalnızca adı değil, orada hangi bilgiyi arayacağın da görünür olacak.</p></header><div className="editor-blueprint">{['Hierarchy','Scene','Game','Inspector','Project','Console'].map((name,index)=><button type="button" key={name} className={`${name.toLowerCase()} ${visited.has(index)?'found':''}`} onClick={()=>{mark(index,Math.min(6,bullets.length+1));setMessage(bullets[index%bullets.length]);}}><b>{index+1}</b><span>{name}</span><small>{visited.has(index)?message:'Keşfet'}</small></button>)}</div></section>;

  if (treeModes.includes(mode)) return <section className={`experience-stage experience-${mode}`}><header><span>YAPI GEZGİNİ</span><h3>Kökü, alt öğeyi ve sahne varlığını birbirine karıştırma.</h3><p>Ağacın dallarını aç; seçimin sonuç yolunu ve kanıtını eş zamanlı izle.</p></header><div className="tree-lab"><div role="tree" aria-label="Etkileşimli yapı ağacı"><button type="button" onClick={()=>mark(0)} className={visited.has(0)?'selected':''}>▾ GameDev</button><button type="button" onClick={()=>mark(1)} className={visited.has(1)?'selected child':''}>▾ Projects</button>{bullets.map((bullet,index)=><button role="treeitem" type="button" key={bullet} className={visited.has(index+2)?'selected leaf':'leaf'} onClick={()=>{mark(index+2,bullets.length+2);setMessage(bullet);}}>└ {bullet}</button>)}</div><aside><small>SEÇİLEN YOL</small><code>D:/GameDev/Projects/{visited.size>1?'LevelUpPractice':'…'}</code><strong>{message}</strong><div className="tree-spotlight" aria-hidden="true"><i/><span>{visited.size}</span></div></aside></div></section>;

  if (sceneModes.includes(mode)) return <section className={`experience-stage experience-${mode}`}><header><span>CANLI SAHNE</span><h3>Sayısal veri ile görsel sonucu aynı anda değiştir.</h3><p>Kontroller yalnız animasyon üretmez; Inspector’daki verinin Scene sonucuna nasıl dönüştüğünü gösterir.</p></header><div className="transform-lab"><div className="transform-scene"><svg viewBox="0 0 520 280" role="img" aria-label="Üç eksenli etkileşimli sahne"><path className="grid" d="M40 220L260 105L480 220L260 270Z M95 191L315 76 M150 162L370 47 M205 133L425 18 M95 249L315 134 M150 278L370 163 M205 307L425 192"/><path className="axis-x" d="M260 180H455"/><path className="axis-y" d="M260 180V30"/><path className="axis-z" d="M260 180L105 250"/><g style={{transform:`translate(${(value-35)*2}px,${mode==='scale'?0:-(value-35)}px) rotate(${mode==='rotation'?value:0}deg) scale(${mode==='scale'?0.55+value/70:1})`,transformOrigin:'260px 180px'}}><rect x="220" y="140" width="80" height="80" rx="8"/><path d="M220 140l35-22h80l-35 22M300 140l35-22v80l-35 22"/></g><text x="463" y="184">X</text><text x="265" y="26">Y</text><text x="91" y="261">Z</text></svg><span>{mode.toUpperCase()} · {value}</span></div><aside><label>Değer <input type="range" min="0" max="90" value={value} onChange={(event)=>{setValue(Number(event.target.value));if(Number(event.target.value)!==35)onReady();}}/><b>{value}</b></label>{bullets.slice(0,4).map((bullet,index)=><button type="button" key={bullet} onClick={()=>{mark(index,Math.min(3,bullets.length));setMessage(bullet);}} className={visited.has(index)?'active':''}>{bullet}</button>)}<p>{message}</p></aside></div></section>;

  if (['connect','components'].includes(mode)) return <section className={`experience-stage experience-${mode}`}><header><span>BAĞLANTI MASASI</span><h3>Parçaları doğru sinyal hattında buluştur.</h3><p>Her bağlantı, bir kaynağın hangi bileşene veri veya davranış taşıdığını görünür kılar.</p></header><div className="connector-lab"><div className="connector-source"><span>GAMEOBJECT</span><b>{mode === 'components' ? 'Cube' : 'Sistem'}</b><i className={visited.size ? 'active' : ''}/></div><div className="connector-lines" aria-hidden="true">{bullets.map((_,index)=><i key={index} className={visited.has(index)?'active':''}/>)}</div><div className="connector-targets">{bullets.map((bullet,index)=><button key={bullet} type="button" className={visited.has(index)?'linked':''} onClick={()=>{mark(index);setMessage(bullet);}}><span>{visited.has(index)?'BAĞLANDI':'BAĞLA'}</span><strong>{bullet}</strong></button>)}</div><p>{message}</p></div></section>;

  if (['channels','sorter','classify','checklist'].includes(mode)) return <section className={`experience-stage experience-${mode}`}><header><span>SINIFLANDIRMA BANDI</span><h3>Aynı listede duran bilgiler aynı görevi taşımayabilir.</h3><p>Bir öğe yeni bölmesine geçtiğinde, onu diğerlerinden ayıran görev de görünür hâle geliyor.</p></header><div className="classification-lab"><aside><small>BEKLEYEN</small>{bullets.map((bullet,index)=><button key={bullet} type="button" disabled={visited.has(index)} onClick={()=>{mark(index);setMessage(bullet);}}><b>{index+1}</b><span>{bullet}</span></button>)}</aside><div className="classification-belt" aria-hidden="true"><i/><i/><i/><span>{visited.size}</span></div><article><small>DOĞRULANAN KANIT</small><strong>{visited.size} / {bullets.length}</strong><p>{message}</p></article></div></section>;

  if (['builder','form'].includes(mode)) return <section className={`experience-stage experience-${mode}`}><header><span>KURULUM TEZGAHI</span><h3>Parçalar bir araya geldikçe sistemin bütünü ortaya çıkıyor.</h3><p>Soldaki her karar, sağdaki canlı özete yeni bir bilgi ekliyor.</p></header><div className="builder-lab"><div>{bullets.map((bullet,index)=><label key={bullet}><span>{bullet}</span><button type="button" className={visited.has(index)?'done':''} onClick={()=>{mark(index);setMessage(`${bullet} alanı yapılandırıldı.`);}}>{visited.has(index)?'Hazır':'Yapılandır'}</button></label>)}</div><aside><small>CANLI PROJE FİŞİ</small><code>{`completed: ${visited.size} / ${bullets.length}`}</code><strong>{visited.size===bullets.length?'YAPI HAZIR':'YAPILANDIRILIYOR'}</strong><div><i style={{width:`${Math.round((visited.size/Math.max(1,bullets.length))*100)}%`}}/></div><p>{message}</p></aside></div></section>;

  if (mode === 'browser') return <section className="experience-stage experience-browser"><header><span>ASSET BROWSER</span><h3>Dosyayı klasör ağacında bul, önizle ve seç.</h3><p>Sol taraftaki klasör yapısı ile sağdaki içerik görünümü farklı sorulara cevap verir.</p></header><div className="asset-browser-lab"><nav><b>Assets</b>{['Scenes','Scripts','Materials','Prefabs'].map((folder,index)=><button key={folder} type="button" className={cursor===index?'active':''} onClick={()=>setCursor(index)}>▸ {folder}</button>)}</nav><main>{bullets.map((bullet,index)=><button key={bullet} type="button" className={visited.has(index)?'selected':''} onClick={()=>{mark(index);setMessage(bullet);}}><i>{index%2?'◇':'▧'}</i><span>{bullet}</span></button>)}</main><footer><small>SEÇİM</small><strong>{message}</strong></footer></div></section>;

  if (['layers','anatomy','roles','inspector'].includes(mode)) return <section className={`experience-stage experience-${mode}`}><header><span>PARÇA–BÜTÜN LABORATUVARI</span><h3>Tek görünen sonucun altındaki sorumlulukları ayır.</h3><p>Katmanı seçtiğinde yalnız o parçanın görevi ve sistemde bıraktığı iz öne çıkar.</p></header><div className="layer-lab"><div className="exploded-object" aria-hidden="true">{bullets.slice(0,5).map((_,index)=><i key={index} className={visited.has(index)?'active':''} style={{'--layer':index} as React.CSSProperties}/>) }<span>CORE</span></div><div>{bullets.map((bullet,index)=><button type="button" key={bullet} className={visited.has(index)?'active':''} onClick={()=>{mark(index);setMessage(bullet);}}><b>{String(index+1).padStart(2,'0')}</b><span>{bullet}</span><Icon name={visited.has(index)?'check':'plus'} /></button>)}</div><p>{message}</p></div></section>;

  if (['compare','viewport'].includes(mode)) return <section className={`experience-stage experience-${mode}`}><header><span>YAN YANA KARŞILAŞTIR</span><h3>Aynı kaynak, iki farklı bakış veya üretim yolu.</h3><p>Kontrolü değiştir; iki yüzeyin hangi kısmının sabit kaldığını gözle.</p></header><div className="compare-lab"><article><small>{mode==='viewport'?'SCENE VIEW':'SEÇENEK A'}</small><div className="viewport-scene" style={{transform:`perspective(500px) rotateY(${value/6-6}deg)`}}><i/><b>◆</b><span>geliştirici bakışı</span></div></article><article><small>{mode==='viewport'?'GAME VIEW':'SEÇENEK B'}</small><div className="viewport-scene fixed"><i/><b>◆</b><span>{toggle?'oyuncu kadrajı':'uyumluluk sonucu'}</span></div></article><footer><label>Bakış / hedef <input type="range" min="0" max="90" value={value} onChange={(event)=>{setValue(Number(event.target.value));onReady();}} /></label><button type="button" className={toggle?'toggle-control on':'toggle-control'} onClick={()=>{setToggle(!toggle);onReady();}}><i/>{toggle?'İkinci kanıt açık':'İkinci kanıtı aç'}</button></footer></div></section>;

  if (['validator','search','ide'].includes(mode)) return <section className={`experience-stage experience-${mode}`}><header><span>CANLI DOĞRULAYICI</span><h3>Yazdığın değer anında başka bir yüzeye dönüşür.</h3><p>Önce dene; değerlendirme yazmayı bitirdiğinde açıklanır.</p></header><div className="validator-lab"><label>{mode==='search'?'Aranacak öğe':mode==='ide'?'Kod editörü bağlantısı':'Proje adı'}<input value={typed} onChange={(event)=>setTyped(event.target.value)} placeholder={mode==='search'?'cam':mode==='ide'?'Rider / Visual Studio':'LevelUpPractice'} /></label><div><small>CANLI ÖNİZLEME</small><code>{mode==='search'?`Filter: ${typed||'—'}`:`D:/GameDev/Projects/${typed||'…'}`}</code><strong>{typed.length>=3?'Okunabilir ve izlenebilir':'En az üç anlamlı karakter gerekli'}</strong></div><button type="button" className="button button-secondary" onClick={completeTyped}>Doğrula<Icon name="check" /></button><p role="status">{message}</p></div></section>;

  if (['filter'].includes(mode)) return <section className="experience-stage experience-filter"><header><span>CONSOLE LABORATUVARI</span><h3>Mesajı silmeden görünümü filtrele.</h3><p>Log, warning ve error sayaçlarını ayrı ayrı aç; Clear ile düzeltme arasındaki farkı gözle.</p></header><div className="console-filter-lab"><nav>{['Log · 6','Warning · 3','Error · 3'].map((label,index)=><button type="button" key={label} className={visited.has(index)?'active':''} onClick={()=>{mark(index,3);setCursor(index);}}>{label}</button>)}</nav><div>{Array.from({length:cursor===0?6:3},(_,index)=><p key={index} className={cursor===2?'error':cursor===1?'warning':''}><b>{cursor===2?'×':cursor===1?'!':'i'}</b><span>{bullets[index%bullets.length]}</span></p>)}</div><footer><span>Filtre görünümü değiştirir; kök neden dosyada kalır.</span></footer></div></section>;

  if (['dock'].includes(mode)) return <section className="experience-stage experience-dock"><header><span>LAYOUT ATÖLYESİ</span><h3>Paneli taşı, çalışma alanını bozmadan geri getir.</h3><p>Bir panel ve hedef bölge seç; ardından varsayılan yerleşimi geri yükle.</p></header><div className="dock-lab"><button onClick={()=>mark(0,3)} className={visited.has(0)?'active':''}>Hierarchy</button><button onClick={()=>mark(1,3)} className={visited.has(1)?'active':''}>Scene</button><button onClick={()=>mark(2,3)} className={visited.has(2)?'active':''}>Inspector</button><button onClick={()=>{setVisited(new Set());setMessage('Varsayılan layout geri yüklendi.');onReady();}} className="dock-reset">Layout’u sıfırla</button></div><p className="dock-status">{message}</p></section>;

  if (['diagnostic','clinic'].includes(mode)) return <section className={`experience-stage experience-${mode}`}><header><span>TANI AĞACI</span><h3>İlk görünen belirti, hatanın başladığı yer olmayabilir.</h3><p>Olası nedenler tek tek sınandıkça, bir sonraki kontrolün neden gerekli olduğu açıklanıyor.</p></header><div className="diagnostic-tree"><div className="diagnostic-root"><small>BELİRTİ</small><strong>{step.title.tr}</strong><i/></div><div className="diagnostic-branches">{bullets.map((bullet,index)=><button key={bullet} type="button" className={visited.has(index)?'tested':''} onClick={()=>{mark(index);setMessage(index===bullets.length-1?'Kök neden kanıtlarla daraltıldı.':`${bullet} kontrol edildi; sonraki dala geç.`);}}><span>{visited.has(index)?'✓':'?'}</span><strong>{bullet}</strong><small>{visited.has(index)?'Kanıt alındı':'Test et'}</small></button>)}</div><aside><small>AKTİF TANI</small><b>{visited.size}/{bullets.length}</b><p>{message}</p></aside></div></section>;

  if (mode === 'evidence') return <section className={`experience-stage experience-${mode}`}><header><span>KANIT ZİNCİRİ</span><h3>Sağlam bir teşhis, tahminden değil birbirini destekleyen kanıtlardan oluşur.</h3><p>Her geçen kontrol olası nedenleri biraz daha daraltıyor.</p></header><div className="evidence-lab"><ol>{bullets.map((bullet,index)=><li key={bullet} className={visited.has(index)?'passed':''}><button type="button" disabled={index>visited.size} onClick={()=>{mark(index);setMessage(index===bullets.length-1?'Bütün kanıtlar tamamlandı.':`${bullet}: geçti; sıradaki kanıta ilerle.`);}}><span>{visited.has(index)?'✓':index===visited.size?'→':'·'}</span><div><strong>{bullet}</strong><small>{visited.has(index)?'Kanıt doğrulandı':index===visited.size?'Kontrol etmeye hazır':'Önceki kanıtı tamamla'}</small></div></button></li>)}</ol><aside><Icon name="gauge" /><small>TANI DURUMU</small><strong>{visited.size} / {bullets.length}</strong><p>{message}</p></aside></div></section>;

  if (['manifest'].includes(mode)) return <section className="experience-stage experience-manifest"><header><span>PROJE MANİFESTİ</span><h3>Kararların tek tek değil, birlikte tutarlı olması gerekir.</h3><p>Satırları denetle; şüpheli bağlantıyı seçip gerekçesini gör.</p></header><div className="manifest-lab"><dl>{bullets.map((bullet,index)=><button type="button" key={bullet} className={visited.has(index)?'checked':''} onClick={()=>{mark(index);setMessage(bullet);}}><dt>{['Editor','Template','Location','Cloud'][index%4]}</dt><dd>{bullet}</dd><span>{visited.has(index)?'✓':'Denetle'}</span></button>)}</dl><aside><i/><strong>MANIFEST / {visited.size===bullets.length?'READY':'CHECK'}</strong><p>{message}</p></aside></div></section>;

  if (['simulator','machine'].includes(mode)) return <section className={`experience-stage experience-${mode}`}><header><span>DURUM MAKİNESİ</span><h3>Bir değeri değiştir; sistemin yeni durumunu izle.</h3><p>Kontroller aynı veri modelini paylaşır. Sonuç, seçtiğin durumdan üretilir.</p></header><div className="state-machine-lab"><div className="machine-display"><small>{mode==='machine'?'EDITOR MODE':'SYSTEM STATE'}</small><strong>{toggle?'ACTIVE':'IDLE'}</strong><b>{value}</b><div><i style={{width:`${value}%`}}/></div><p>{bullets[cursor%bullets.length]}</p></div><aside><button type="button" className={toggle?'toggle-control on':'toggle-control'} onClick={()=>{setToggle(!toggle);onReady();}}><i/>{toggle?'Çalışıyor':'Başlat'}</button><label>Durum değeri <input type="range" min="0" max="100" value={value} onChange={(event)=>{setValue(Number(event.target.value));onReady();}}/></label><button type="button" onClick={()=>setCursor((cursor+1)%bullets.length)}>Sonraki durumu gözle</button></aside></div></section>;

  return <section className={`experience-stage experience-${mode}`}><header><span>UYGULAMA ALANI</span><h3>Bu bölümde kavramın ekrandaki karşılığını birlikte kuracağız.</h3><p>Her kontrol yeni bir kanıt gösteriyor; bütün parçalar tamamlandığında kısa değerlendirme açılıyor.</p></header><div className="mission-lab"><div className="mission-board"><small>GÖREV / {mode.toUpperCase()}</small><div className="mission-radar" aria-hidden="true"><i/><i/><span>{visited.size}</span></div><strong>{visited.size === bullets.length ? 'GÖREV HAZIR' : 'KANIT TOPLANIYOR'}</strong><p>{message}</p></div><ol>{bullets.map((bullet,index)=><li key={bullet}><button type="button" className={visited.has(index)?'done':''} onClick={()=>{mark(index);setMessage(bullet);}}><span>{visited.has(index)?'✓':index+1}</span><strong>{bullet}</strong></button></li>)}</ol></div></section>;
}

export function FoundationActivity({ step, locale, completed, onComplete }: { step: LessonStep; locale: Locale; completed: boolean; onComplete: () => void }) {
  const [explored, setExplored] = useState(false);
  const [selected, setSelected] = useState<number | null>(null);
  const [reflection, setReflection] = useState('');
  const [attempts, setAttempts] = useState(0);
  const challenge = challenges[step.id];
  const bullets = localize(step.bullets, locale);
  const correct = selected === challenge?.answer;
  const needsReflection = step.kind === 'lab' || step.kind === 'debug' || step.kind === 'test' || step.kind === 'game';
  const canComplete = explored && correct && (!needsReflection || reflection.trim().length >= 20);
  const progress = useMemo(() => {
    const explorePart = explored ? 1 : 0;
    const answerPart = correct ? 1 : 0;
    const reflectionPart = !needsReflection ? 1 : Math.min(1, reflection.trim().length / 20);
    return Math.round(((explorePart + answerPart + reflectionPart) / 3) * 100);
  }, [correct, explored, needsReflection, reflection]);

  if (!challenge) return null;

  const choose = (index: number) => {
    setSelected(index);
    setAttempts((value) => value + 1);
  };

  return (
    <section className={`foundation-activity foundation-${step.kind} lesson-theme-${step.id.split('-')[0]} step-theme-${step.id}`} aria-labelledby={`${step.id}-activity-title`}>
      <header className="foundation-hero">
        <div>
          <p className="section-kicker">{kindLabel[step.kind]} · {step.xp} XP</p>
          <h2 id={`${step.id}-activity-title`}>{localize(step.objective, locale)}</h2>
          <p>{localize(step.description, locale)}</p>
        </div>
        <div className="foundation-progress" aria-label={`Etkinlik ilerlemesi yüzde ${progress}`}><span>{progress}%</span><i><b style={{ width:`${progress}%` }} /></i></div>
      </header>

      <div className="learning-rhythm" aria-label="Öğrenme sırası">
        <span className="active"><b>1</b> Anla</span><i />
        <span className={explored ? 'active' : ''}><b>2</b> Keşfet</span><i />
        <span className={correct ? 'active' : ''}><b>3</b> Uygula</span><i />
        <span className={canComplete ? 'active' : ''}><b>4</b> Kanıtla</span>
      </div>

      {hasSignatureExperience(step.id)
        ? <SignatureExperience stepId={step.id} onReady={() => setExplored(true)} />
        : <ExperienceStage step={step} bullets={bullets} onReady={() => setExplored(true)} />}

      <section className={explored ? 'challenge-stage ready' : 'challenge-stage locked'} aria-disabled={!explored}>
        <div className="challenge-heading"><span className="stage-number">02</span><div><p className="section-kicker">KISA BİR KONTROL</p><h3>{challenge.prompt}</h3><p>{explored ? 'İlk düşünceni işaretleyebilirsin. Yanlış çıkarsa açıklama kaybolmaz ve yeniden deneyebilirsin.' : 'Bu soru, yukarıdaki deneyim tamamlandığında açılacak.'}</p></div></div>
        <div className="challenge-options">
          {challenge.options.map((option, index) => <button key={option} type="button" disabled={!explored || correct} className={selected === index ? (index === challenge.answer ? 'correct' : 'incorrect') : correct && index === challenge.answer ? 'correct' : ''} onClick={() => choose(index)}><b>{String.fromCharCode(65 + index)}</b><span>{option}</span>{selected === index && <Icon name={index === challenge.answer ? 'check' : 'close'} />}</button>)}
        </div>
        {selected !== null && <div className={correct ? 'foundation-feedback correct' : 'foundation-feedback incorrect'} role="status"><Icon name={correct ? 'check' : 'spark'} /><div><strong>{correct ? 'Kanıt doğru.' : 'Henüz değil; seçim hakkın devam ediyor.'}</strong><p>{correct ? challenge.explanation : challenge.hint}</p></div></div>}
      </section>

      {needsReflection && correct && <section className="reflection-stage"><span className="stage-number">03</span><div><p className="section-kicker">SEN NASIL AÇIKLARDIN?</p><h3>Kararın arkasındaki nedeni birkaç cümleyle anlatabilirsin.</h3><p>Burada kusursuz bir teknik tanım aranmıyor. Önemli olan, gördüğün sonuç ile verdiğin karar arasında kendi cümlenle bir bağ kurabilmen.</p><textarea value={reflection} onChange={(event) => setReflection(event.target.value)} placeholder="Ben bu seçimi yaptım çünkü…" maxLength={320} /><small>{reflection.trim().length} / 20 gerekli</small></div></section>}

      <footer className="foundation-complete">
        <div><Icon name={completed ? 'check' : canComplete ? 'spark' : 'lock'} /><span><strong>{completed ? 'Bu adımı tamamladın.' : canComplete ? 'Öğrenme kanıtın hazır.' : 'Tamamlama için keşif ve uygulama gerekli.'}</strong><small>{attempts > 1 ? `${attempts} deneme · yanlışlar XP silmedi` : localize(step.transition, locale)}</small></span></div>
        <button type="button" className="button button-primary" disabled={!canComplete || completed} onClick={onComplete}>{completed ? 'Tamamlandı' : 'İlerle'}<Icon name={completed ? 'check' : 'arrow-right'} /></button>
      </footer>
    </section>
  );
}
