import { useMemo, useState } from 'react';
import type { Locale } from '../domain/models';
import type { LessonActivityKind } from '../learning/course';
import { Icon } from '../shared/Icon';

interface LessonActivityProps {
  kind: Exclude<LessonActivityKind, 'code'>;
  locale: Locale;
  onComplete: () => void;
}

const copy = (locale: Locale, tr: string, en: string) => locale === 'tr' ? tr : en;

export function LessonActivity({ kind, locale, onComplete }: LessonActivityProps) {
  const components: Record<Exclude<LessonActivityKind, 'code'>, React.ReactNode> = {
    brief: <Brief locale={locale} onComplete={onComplete} />,
    hotspot: <Hotspot locale={locale} onComplete={onComplete} />,
    reveal: <Reveal locale={locale} onComplete={onComplete} />,
    match: <Match locale={locale} onComplete={onComplete} />,
    order: <Order locale={locale} onComplete={onComplete} />,
    fill: <Fill locale={locale} onComplete={onComplete} />,
    inspector: <Inspector locale={locale} onComplete={onComplete} />,
    predict: <Predict locale={locale} onComplete={onComplete} />,
    spot: <Spot locale={locale} onComplete={onComplete} />,
    sort: <Sort locale={locale} onComplete={onComplete} />,
    console: <ConsoleDetective locale={locale} onComplete={onComplete} />,
    mastery: <Mastery locale={locale} onComplete={onComplete} />,
  };
  return <section className="activity-studio">{components[kind]}</section>;
}

function ActivityHeader({ eyebrow, title, body, progress }: { eyebrow: string; title: string; body: string; progress?: string }) {
  return <header className="activity-header"><div><p className="section-kicker">{eyebrow}</p><h2><TechnicalInline text={title} /></h2><p><TechnicalInline text={body} /></p></div>{progress && <span>{progress}</span>}</header>;
}

function Done({ children }: { children: React.ReactNode }) {
  return <p className="activity-feedback success"><Icon name="check" />{typeof children === 'string' ? <TechnicalInline text={children} /> : children}</p>;
}

function TechnicalInline({ text }: { text: string }) {
  return <>{text.split('`').map((part, index) => index % 2 ? <code key={`${part}-${index}`}>{part}</code> : part)}</>;
}

function TeachingGate({ locale, onOpen }: { locale: Locale; onOpen: () => void }) {
  return <button className="button button-primary teaching-gate" type="button" onClick={onOpen}>{copy(locale, 'Anladım, kısa uygulamayı aç', 'I understand—open the short practice')}<Icon name="arrow-right" /></button>;
}

function Brief({ locale, onComplete }: Omit<LessonActivityProps, 'kind'>) {
  const [done, setDone] = useState(false);
  return <><ActivityHeader eyebrow={copy(locale, 'Zihinsel model', 'Mental model')} title={copy(locale, 'Koddan önce resmi kur.', 'Build the picture before code.')} body={copy(locale, 'Bu derste her kavramı önce görecek, sonra dokunacak, en son yazacaksın. Kod editörü hedef değil; öğrendiğini sınadığın araç.', 'In this lesson you will first see, then interact, and only then write. The code editor is not the goal; it is where you test understanding.')} /><div className="concept-flow"><article><b>1</b><strong>{copy(locale, 'Gör', 'See')}</strong><span>{copy(locale, 'Unity’deki karşılığını tanı.', 'Recognise it in Unity.')}</span></article><article><b>2</b><strong>{copy(locale, 'Dene', 'Try')}</strong><span>{copy(locale, 'Değiştir ve sonucu izle.', 'Change it and observe.')}</span></article><article><b>3</b><strong>{copy(locale, 'Açıkla', 'Explain')}</strong><span>{copy(locale, 'Nedenini kendi cümlenle kur.', 'State the reason in your words.')}</span></article><article><b>4</b><strong>{copy(locale, 'Yaz', 'Write')}</strong><span>{copy(locale, 'Kodu sıfırdan üret.', 'Produce the code from scratch.')}</span></article></div>{done ? <Done>{copy(locale, 'Ders yöntemini biliyorsun. Sonraki adımda Unity Editor’ü keşfedeceksin.', 'You know the method. Next you will explore the Unity Editor.')}</Done> : <button className="button button-primary activity-primary" type="button" onClick={() => { setDone(true); onComplete(); }}>{copy(locale, 'Hazırım, keşfe başla', 'I’m ready—start exploring')}<Icon name="arrow-right" /></button>}</>;
}

function Hotspot({ locale, onComplete }: Omit<LessonActivityProps, 'kind'>) {
  const points = [
    ['Hierarchy', copy(locale, 'Sahnedeki GameObject listesidir. Nesneyi burada seçer, ebeveyn–çocuk ilişkisini burada görürsün.', 'The list of GameObjects in the scene. Select objects and inspect parent-child relationships here.')],
    ['Scene', copy(locale, 'Sahneyi kurduğun çalışma alanıdır. Bu görünüm oyunun kamera çıktısı değildir.', 'The workspace where you build the scene. It is not the camera output.')],
    ['Game', copy(locale, 'Aktif Camera’nın oyuncuya göstereceği sonucu önizler.', 'Previews what the active Camera will show the player.')],
    ['Inspector', copy(locale, 'Seçili nesnenin Component ve ayarlarını gösterir.', 'Shows the selected object’s Components and settings.')],
    ['Project', copy(locale, 'Diskteki Assets klasörünün proje içindeki görünümüdür.', 'The project view of the Assets folder on disk.')],
    ['Console', copy(locale, 'Log, warning ve error mesajlarını dosya ve satır bilgisiyle gösterir.', 'Shows logs, warnings, and errors with file and line information.')],
  ] as const;
  const [seen, setSeen] = useState<Set<string>>(new Set());
  const [active, setActive] = useState(0);
  const pick = (name: string, index: number) => { const next = new Set(seen).add(name); setSeen(next); setActive(index); if (next.size === points.length) onComplete(); };
  return <><ActivityHeader eyebrow={copy(locale, 'Panel avı', 'Panel hunt')} title={copy(locale, 'Unity Editor’ü haritadan öğren.', 'Learn the Unity Editor as a map.')} body={copy(locale, 'Altı panelin her birine dokun. İsim ezberlemek yerine panelin hangi soruya cevap verdiğini bul.', 'Tap all six panels. Learn the question each panel answers instead of memorising names.')} progress={`${seen.size} / ${points.length}`} /><div className="unity-map"><div className="unity-map-bar"><i /><i /><i /><span>SampleScene — Unity</span></div><button className="panel hierarchy" onClick={() => pick('Hierarchy',0)}><strong>Hierarchy</strong><span>Player<br/>Main Camera<br/>Ground</span></button><button className="panel scene" onClick={() => pick('Scene',1)}><strong>Scene</strong><span className="scene-cube" /></button><button className="panel game" onClick={() => pick('Game',2)}><strong>Game</strong><span className="scene-cube solid" /></button><button className="panel inspector" onClick={() => pick('Inspector',3)}><strong>Inspector</strong><span>Transform<br/>Script<br/>Collider</span></button><button className="panel project" onClick={() => pick('Project',4)}><strong>Project</strong><span>Assets / Scripts</span></button><button className="panel console" onClick={() => pick('Console',5)}><strong>Console</strong><span>Log · Warning · Error</span></button></div><div className="activity-explanation"><strong>{points[active][0]}</strong><p>{points[active][1]}</p></div>{seen.size === points.length && <Done>{copy(locale, 'Altı paneli keşfettin. Artık “nerede aramalıyım?” sorusunu daha doğru cevaplayabilirsin.', 'You explored all six panels and can better answer “where should I look?”')}</Done>}</>;
}

function Reveal({ locale, onComplete }: Omit<LessonActivityProps, 'kind'>) {
  const cards = [
    ['Script', copy(locale, '`.cs` uzantılı kaynak dosyasıdır. Tek başına sahnede çalışmaz.', 'A `.cs` source file. It does not run in the scene by itself.')],
    ['Class', copy(locale, 'Veri ve davranışın şablonudur. Component bu şablondan oluşan örnektir.', 'A blueprint for data and behaviour. A Component is an instance of it.')],
    ['GameObject', copy(locale, 'Sahnedeki taşıyıcı nesnedir. Davranışı Component’lerden gelir.', 'A container object in the scene. Its behaviour comes from Components.')],
    ['Component', copy(locale, 'GameObject’e eklenen tek bir sorumluluk parçasıdır.', 'A single responsibility attached to a GameObject.')],
  ];
  const [open,setOpen]=useState<Set<number>>(new Set());
  const toggle=(i:number)=>{const next=new Set(open); next.add(i); setOpen(next); if(next.size===cards.length)onComplete();};
  return <><ActivityHeader eyebrow={copy(locale,'Dokun ve aç','Tap to reveal')} title={copy(locale,'Dosya, şablon ve sahne nesnesini ayır.','Separate file, blueprint, and scene object.')} body={copy(locale,'Dört kartı aç. Sonra “script ile Component aynı şey midir?” sorusuna cevap ver.','Open all four cards, then answer whether a script and Component are the same thing.')} progress={`${open.size} / 4`} /><div className="reveal-grid">{cards.map((card,i)=><button key={card[0]} type="button" className={open.has(i)?'reveal-card open':'reveal-card'} onClick={()=>toggle(i)} aria-expanded={open.has(i)}><span>{open.has(i)?'−':'+'}</span><strong>{card[0]}</strong>{open.has(i)&&<p><TechnicalInline text={card[1]} /></p>}</button>)}</div>{open.size===cards.length&&<Done>{copy(locale,'Doğru ayrım: Script dosyadır; sınıf şablondur; Component sahnedeki örnektir.','Correct: a script is a file, a class is a blueprint, and a Component is the scene instance.')}</Done>}</>;
}

function Match({ locale, onComplete }: Omit<LessonActivityProps, 'kind'>) {
  const pairs=[['using',copy(locale,'Namespace içindeki türlere kısa adla erişir','Accesses namespace types by short name')],['class',copy(locale,'Yeni bir türün şablonunu tanımlar','Defines a new type blueprint')],['MonoBehaviour',copy(locale,'Sınıfı bir Unity Component olarak kullanılabilir hâle getirir','Makes the class usable as a Unity Component')],['{ }',copy(locale,'Bir scope’un başlangıç ve bitişini belirler','Defines the boundaries of a scope')]];
  const order=[2,0,3,1]; const [practice,setPractice]=useState(false); const [left,setLeft]=useState<number|null>(null); const [matched,setMatched]=useState<Set<number>>(new Set()); const [wrong,setWrong]=useState<number|null>(null);
  const choose=(right:number)=>{if(left===null)return;if(left===right){const next=new Set(matched).add(left);setMatched(next);setLeft(null);if(next.size===pairs.length)onComplete();}else{setWrong(right);setTimeout(()=>setWrong(null),500);}};
  if (!practice) return <>
    <ActivityHeader eyebrow={copy(locale,'Önce öğren','Learn first')} title={copy(locale,'Bir Unity scriptinin dört yapı taşı','Four building blocks of a Unity script')} body={copy(locale,'Bu kelimeleri ezberlemeyeceğiz. Her birinin kodda hangi sorunu çözdüğünü, gerçek bir script üzerinde göreceğiz.','We will not memorise these words. We will see which problem each one solves in a real script.')} />
    <div className="anatomy-lesson">
      <div className="anatomy-code" aria-label={copy(locale,'Açıklamalı C sharp sınıfı','Annotated C sharp class')}>
        <div className="code-filebar"><i/><i/><i/><span>FirstScript.cs</span></div>
        <pre><code><span className="code-row"><b>1</b><mark>1</mark><span className="syntax-keyword">using</span> <span className="syntax-api">UnityEngine</span>;</span>{'\n'}<span className="code-row empty"><b>2</b></span>{'\n'}<span className="code-row"><b>3</b><span className="syntax-keyword">public class</span> <span className="syntax-type">FirstScript</span> : <mark>3</mark><span className="syntax-api">MonoBehaviour</span></span>{'\n'}<span className="code-row"><b>4</b><mark>4</mark>{'{'}</span>{'\n'}<span className="code-row"><b>5</b>    <span className="syntax-comment">// Davranışlar bu alanın içine yazılır.</span></span>{'\n'}<span className="code-row"><b>6</b>{'}'}</span></code></pre>
        <span className="class-marker">2</span>
      </div>
      <div className="anatomy-cards">
        <article><span>1</span><div><code>using UnityEngine;</code><strong>{copy(locale,'Uzun adresin kısa yolu','A shortcut for a long address')}</strong><p><TechnicalInline text={copy(locale,'Bu satır bir nesne oluşturmaz ve oyunu başlatmaz. `UnityEngine.MonoBehaviour` yazmak yerine `MonoBehaviour` diyebilmeni sağlar. Bir telefon rehberinde tam numara yerine kayıtlı adı kullanmak gibidir.','This line creates no object and starts no game. It lets you write `MonoBehaviour` instead of `UnityEngine.MonoBehaviour`, like using a saved contact name instead of the full number.')} /></p></div></article>
        <article><span>2</span><div><code>class FirstScript</code><strong>{copy(locale,'Nesnenin kendisi değil, tarifi','A recipe, not the object itself')}</strong><p><TechnicalInline text={copy(locale,'`class`, veri ve davranışların nasıl bir araya geleceğini tarif eden şablondur. Bir düşman sınıfı “canı ve hareketi vardır” der; sahnedeki her düşman bu tariften üretilen ayrı bir örnektir.','A `class` is a blueprint describing how data and behaviour fit together. An Enemy class says it has health and movement; each enemy in the scene is a separate instance.')} /></p></div></article>
        <article><span>3</span><div><code>: MonoBehaviour</code><strong>{copy(locale,'C# sınıfından Unity Component’ine','From C# class to Unity Component')}</strong><p><TechnicalInline text={copy(locale,'Bu kalıtım sayesinde sınıf GameObject’e Component olarak eklenebilir ve Unity’nin `Awake`, `Start` gibi yaşam döngüsü mesajlarına katılabilir. Her C# sınıfı kendiliğinden bir Component değildir.','This inheritance lets the class be attached to a GameObject as a Component and participate in lifecycle messages such as `Awake` and `Start`. Not every C# class is automatically a Component.')} /></p></div></article>
        <article><span>4</span><div><code>{'{  }'}</code><strong>{copy(locale,'Kodun odası: scope','The room of the code: scope')}</strong><p><TechnicalInline text={copy(locale,'Açılan `{` odanın kapısı, kapanan `}` ise sınırıdır. Sınıfa ait alanlar ve metotlar bu iki sınırın içinde bulunur. Yanlış yerde kapanan parantez, yapının anlamını bozar.','The opening `{` is the door and `}` is the boundary. Fields and methods belonging to the class live inside these boundaries. A misplaced brace changes the structure.')} /></p></div></article>
      </div>
    </div>
    <TeachingGate locale={locale} onOpen={()=>setPractice(true)} />
  </>;
  return <><ActivityHeader eyebrow={copy(locale,'Şimdi uygula','Now practise')} title={copy(locale,'Terimi görevine bağla.','Connect each term to its job.')} body={copy(locale,'Önce soldan bir terim, sonra sağdan görevi seç. Kararsız kalırsan üstte öğrendiğin “hangi sorunu çözüyor?” düşüncesini kullan.','Pick a term on the left, then its job on the right. If unsure, ask which problem it solves.')} progress={`${matched.size} / 4`} /><div className="practice-recap"><code><span className="syntax-keyword">using</span> UnityEngine;</code><span>→</span><code><span className="syntax-keyword">class</span> FirstScript</code><span>→</span><code>: <span className="syntax-api">MonoBehaviour</span></code><span>→</span><code>{'{  }'}</code></div><div className="match-board"><div>{pairs.map((p,i)=><button key={p[0]} disabled={matched.has(i)} className={left===i?'selected':matched.has(i)?'matched':''} onClick={()=>setLeft(i)}>{matched.has(i)&&<Icon name="check"/>}<code>{p[0]}</code></button>)}</div><div>{order.map(i=><button key={i} disabled={matched.has(i)||left===null} className={wrong===i?'wrong':matched.has(i)?'matched':''} onClick={()=>choose(i)}>{pairs[i][1]}</button>)}</div></div>{matched.size===4&&<Done>{copy(locale,'Her yapı taşını göreviyle eşleştirdin. Sıradaki adımda bu parçaları gerçek sınıf sırasına koyacaksın.','You matched every building block to its job. Next you will put them in a real class order.')}</Done>}</>;
}

function Order({ locale, onComplete }: Omit<LessonActivityProps, 'kind'>) {
  const items=['using UnityEngine;','public class FirstScript : MonoBehaviour','{','}']; const [order,setOrder]=useState([1,2,0,3]); const [checked,setChecked]=useState(false); const correct=order.every((x,i)=>x===i);
  const move=(i:number,d:number)=>{const j=i+d;if(j<0||j>=order.length)return;const next=[...order];[next[i],next[j]]=[next[j],next[i]];setOrder(next);setChecked(false);};
  return <><ActivityHeader eyebrow={copy(locale,'Sıraya koy','Put in order')} title={copy(locale,'Derlenebilir sınıf iskeletini kur.','Build a compilable class skeleton.')} body={copy(locale,'Satırları sürüklemek yerine oklarla taşı. Böylece dokunmatik ekranda sayfa kaydırma davranışı bozulmaz.','Move lines with arrows rather than dragging, preserving touch scrolling.')} /><ol className="order-list">{order.map((item,pos)=><li className={checked?(item===pos?'right':'wrong'):''} key={item}><span>{pos+1}</span><code>{items[item]}</code><div><button onClick={()=>move(pos,-1)} disabled={pos===0}>↑</button><button onClick={()=>move(pos,1)} disabled={pos===3}>↓</button></div></li>)}</ol>{checked&&correct?<Done>{copy(locale,'Doğru sıra. `using` sınıfın dışında; açılış ve kapanış parantezleri sınıfın scope’unu çevreliyor.','Correct. `using` is outside the class and the braces surround its scope.')}</Done>:<button className="button button-primary activity-primary" onClick={()=>{setChecked(true);if(correct)onComplete();}}>{checked?copy(locale,'Tekrar kontrol et','Check again'):copy(locale,'Sırayı kontrol et','Check order')}</button>}</>;
}

function Fill({ locale, onComplete }: Omit<LessonActivityProps, 'kind'>) {
  const answers=['public','FirstScript','MonoBehaviour']; const pool=['MonoBehaviour','private','FirstScript','GameObject','public']; const [slots,setSlots]=useState<(string|null)[]>([null,null,null]); const [checked,setChecked]=useState(false); const solved=checked&&slots.every((x,i)=>x===answers[i]);
  const place=(token:string)=>{const i=slots.indexOf(null);if(i<0)return;const next=[...slots];next[i]=token;setSlots(next);setChecked(false);};
  return <><ActivityHeader eyebrow={copy(locale,'Boşluk doldurma','Fill the blanks')} title={copy(locale,'Sınıf bildirimini tamamla.','Complete the class declaration.')} body={copy(locale,'Token havuzundan seç. Buradaki hedef yazma hızı değil, sözdiziminin parçalarını tanımak.','Choose from the token pool. The goal is recognising syntax, not typing speed.')} /><div className="fill-code"><code><button onClick={()=>{const n=[...slots];n[0]=null;setSlots(n)}}>{slots[0]??'___'}</button> class <button onClick={()=>{const n=[...slots];n[1]=null;setSlots(n)}}>{slots[1]??'___'}</button> : <button onClick={()=>{const n=[...slots];n[2]=null;setSlots(n)}}>{slots[2]??'___'}</button></code></div><div className="token-pool">{pool.map((x,i)=><button key={`${x}-${i}`} onClick={()=>place(x)} disabled={!slots.includes(null)}><code>{x}</code></button>)}<button onClick={()=>{setSlots([null,null,null]);setChecked(false)}}>{copy(locale,'Temizle','Clear')}</button></div>{solved?<Done>{copy(locale,'Bildirim doğru. `public` erişimi, `class` türü, `:` ise kalıtımı tanımlıyor.','Correct. `public` defines access, `class` the type, and `:` inheritance.')}</Done>:<button className="button button-primary activity-primary" disabled={slots.includes(null)} onClick={()=>{setChecked(true);if(slots.every((x,i)=>x===answers[i]))onComplete();}}>{checked?copy(locale,'Bir parça yanlış, yeniden dene','One token is wrong—try again'):copy(locale,'Yapıyı kontrol et','Check structure')}</button>}</>;
}

function Inspector({ locale, onComplete }: Omit<LessonActivityProps, 'kind'>) {
  const [speed,setSpeed]=useState(3);const [output,setOutput]=useState('');
  const run=()=>{setOutput(`Console · speed = ${speed}`);if(speed===6)onComplete();};
  return <><ActivityHeader eyebrow={copy(locale,'Canlı Inspector','Live Inspector')} title={copy(locale,'Kod ile Inspector arasındaki bağı gör.','See the link between code and Inspector.')} body={copy(locale,'Speed değerini 6 yapıp Play’e bas. Alanın kodda private kalırken Inspector’da neden göründüğünü incele.','Set Speed to 6 and press Play. Observe why the field appears in the Inspector while remaining private in code.')} /><div className="inspector-lab"><pre><code><span>[SerializeField]</span>{'\n'}private float speed = 3f;{'\n\n'}void Start(){'\n'}{'{'}{'\n'}    Debug.Log(speed);{'\n'}{'}'}</code></pre><div className="mock-inspector"><strong>First Script (Script)</strong><label>Speed <input type="range" min="1" max="10" value={speed} onChange={e=>setSpeed(Number(e.target.value))}/><code>{speed}</code></label><button className="button button-primary" onClick={run}>▶ Play</button>{output&&<output>{output}</output>}</div></div>{speed===6&&output&&<Done>{copy(locale,'Inspector’daki değer, serileştirilmiş field’ın o Component örneğindeki değeridir.','The Inspector value belongs to the serialised field on that Component instance.')}</Done>}</>;
}

function Predict({ locale, onComplete }: Omit<LessonActivityProps, 'kind'>) {
  const [practice,setPractice]=useState(false);const [pick,setPick]=useState<number|null>(null);const choices=[copy(locale,'Unity her ikisini de otomatik çağırır.','Unity invokes both automatically.'),copy(locale,'Yalnızca `Awake` otomatik çağrılır.','Only `Awake` is invoked automatically.'),copy(locale,'Yalnızca `awake` otomatik çağrılır.','Only `awake` is invoked automatically.')];
  if (!practice) return <>
    <ActivityHeader eyebrow={copy(locale,'Önce öğren','Learn first')} title={copy(locale,'Bir harf, davranışı tamamen değiştirir.','One letter changes the behaviour completely.')} body={copy(locale,'C# büyük ve küçük harfleri farklı kabul eder. Unity ise yaşam döngüsü metotlarını adı birebir doğruysa otomatik çağırır.','C# treats uppercase and lowercase letters as different. Unity automatically invokes lifecycle methods only when their names match exactly.')} />
    <div className="learning-goal-band"><span>{copy(locale,'BU ADIMDA TAM OLARAK NE ÖĞRENİYORUZ?','WHAT EXACTLY ARE WE LEARNING?')}</span><strong>{copy(locale,'Metod yazmayı değil; normal bir C# metodu ile Unity callback’i arasındaki çağrılma farkını.','Not how to write a method, but the invocation difference between a regular C# method and a Unity callback.')}</strong><p><TechnicalInline text={copy(locale,'`void` dönüş türüdür, `Awake` metodun adıdır, `()` parametre listesidir, `{ }` ise gövdedir. Kritik nokta metodun şekli değil, Unity’nin otomatik akışta tam olarak `Awake` adını aramasıdır.','`void` is the return type, `Awake` is the method name, `()` is the parameter list, and `{ }` is the body. The critical point is not the method shape but that Unity looks for the exact name `Awake` in its automatic flow.')} /></p></div>
    <div className="case-lesson">
      <div className="case-comparison">
        <article className="case-card works"><div className="case-card-head"><span>{copy(locale,'Unity tarafından tanındı','Recognised by Unity')}</span><b>✓</b></div><pre><code><span className="syntax-keyword">void</span> <span className="syntax-method">Awake</span>(){`\n`}{'{'}{`\n`}    <span className="syntax-api">Debug</span>.<span className="syntax-method">Log</span>(<span className="syntax-string">"A"</span>);{`\n`}{'}'}</code></pre><p><TechnicalInline text={copy(locale,'Kod derlenir. GameObject yüklenirken Unity bu metodu otomatik çağırır ve Console’da A görünür.','The code compiles. Unity invokes it automatically as the GameObject loads, and A appears in the Console.')} /></p></article>
        <article className="case-card waits"><div className="case-card-head"><span>{copy(locale,'Normal C# metodu','Regular C# method')}</span><b>!</b></div><pre><code><span className="syntax-keyword">void</span> <span className="syntax-method">awake</span>(){`\n`}{'{'}{`\n`}    <span className="syntax-api">Debug</span>.<span className="syntax-method">Log</span>(<span className="syntax-string">"B"</span>);{`\n`}{'}'}</code></pre><p><TechnicalInline text={copy(locale,'Bu da derlenebilir; fakat Unity `awake` adını yaşam döngüsü mesajı olarak tanımaz. Sen başka bir yerden `awake();` çağırmadıkça B görünmez.','This also compiles, but Unity does not recognise `awake` as a lifecycle message. B appears only if you call `awake();` yourself.')} /></p></article>
      </div>
      <div className="lifecycle-track" aria-label={copy(locale,'Unity başlangıç sırası','Unity startup order')}><span className="object-dot">GameObject</span><i/><span className="life-step active"><code>Awake()</code><small>Console · A</small></span><i/><span className="life-step"><code>OnEnable()</code></span><i/><span className="life-step"><code>Start()</code></span><span className="bypassed"><code>awake()</code><small>{copy(locale,'otomatik akışın dışında','outside automatic flow')}</small></span></div>
      <div className="analogy-note"><strong>{copy(locale,'Gerçek hayat bağlantısı','Real-life connection')}</strong><p><TechnicalInline text={copy(locale,'Telefon kilidindeki parola gibi düşün: “Furkan” ile “furkan” göze benzer, fakat sistem için aynı karakter dizisi değildir. Unity’nin beklediği parola tam olarak `Awake` biçimindedir.','Think of a phone password: “Furkan” and “furkan” look similar, but they are not the same character sequence. Unity expects exactly `Awake`.')} /></p></div>
    </div>
    <TeachingGate locale={locale} onOpen={()=>setPractice(true)} />
  </>;
  return <><ActivityHeader eyebrow={copy(locale,'Şimdi tahmin et','Now predict')} title={copy(locale,'`Awake` ile `awake` aynı davranır mı?','Do `Awake` and `awake` behave the same?')} body={copy(locale,'İkisinin de derlenebildiğini biliyorsun. Şimdi Unity’nin hangisini kendiliğinden çağıracağını seç.','You know both can compile. Now choose which one Unity invokes by itself.')} /><div className="compact-code-compare"><pre><code><span className="syntax-keyword">void</span> <span className="syntax-method">Awake</span>() {'{'} <span className="syntax-api">Debug</span>.Log(<span className="syntax-string">"A"</span>); {'}'}</code></pre><pre><code><span className="syntax-keyword">void</span> <span className="syntax-method">awake</span>() {'{'} <span className="syntax-api">Debug</span>.Log(<span className="syntax-string">"B"</span>); {'}'}</code></pre></div><div className="choice-list">{choices.map((x,i)=><button className={pick===i?(i===1?'correct':'incorrect'):''} key={x} onClick={()=>{setPick(i);if(i===1)onComplete();}}><b>{String.fromCharCode(65+i)}</b><TechnicalInline text={x}/></button>)}</div>{pick!==null&&(pick===1?<Done><TechnicalInline text={copy(locale,'Doğru. İki metot da C# açısından geçerlidir; ancak Unity yalnızca tam adı `Awake` olan callback’i otomatik çağırır.','Correct. Both are valid C#, but Unity automatically invokes only the callback named exactly `Awake`.')} /></Done>:<p className="activity-feedback error"><TechnicalInline text={copy(locale,'C# case-sensitive çalışır. Unity callback adı beklenen `Awake` yazımıyla birebir eşleşmelidir.','C# is case-sensitive. The callback name must exactly match Unity’s expected spelling: `Awake`.')} /></p>)}</>;
}

function Spot({ locale, onComplete }: Omit<LessonActivityProps, 'kind'>) {
  const lines=['using UnityEngine;','','public class FirstScript : MonoBehaviour','{','    void Start()','    {','        İlk mesajını buraya yaz.','    }','}'];const [selected,setSelected]=useState<number|null>(null);const right=6;
  return <><ActivityHeader eyebrow={copy(locale,'Hata avı','Spot the error')} title={copy(locale,'Derlemeyi durduran satırı bul.','Find the line that stops compilation.')} body={copy(locale,'Console’un “geçersiz ifade” dediğini varsay. Hatalı satıra dokun; boş satırlar da gerçek satır numarasına dahildir.','Assume the Console reports an invalid expression. Tap the faulty line; blank lines count in line numbers.')} /><ol className="spot-code">{lines.map((x,i)=><li key={i}><button className={selected===i?(i===right?'correct':'incorrect'):''} onClick={()=>{setSelected(i);if(i===right)onComplete();}}><span>{i+1}</span><code>{x||' '}</code></button></li>)}</ol>{selected!==null&&(selected===right?<Done>{copy(locale,'7. satır düz metin. Açıklama olacaksa `//`, çıktı olacaksa `Debug.Log("...");` gerekir.','Line 7 is plain text. Use `//` for a comment or `Debug.Log("...");` for output.')}</Done>:<p className="activity-feedback error">{copy(locale,'Bu satır geçerli. Console’daki satır numarasını ve komut olmayan ifadeyi birlikte ara.','This line is valid. Use the Console line number and look for a non-statement.')}</p>)}</>;
}

function Sort({ locale, onComplete }: Omit<LessonActivityProps, 'kind'>) {
  const items=[['42','int','Tırnaksız tam sayı.'],['"Deniz"','string','Çift tırnak içindeki karakter dizisi.'],['true','bool','İki durumlu mantıksal değer.'],['-3','int','Negatif olsa da tam sayıdır.'],['"Unity hazır"','string','Oyuncuya veya geliştiriciye gösterilen metin.'],['false','bool','Olumsuz mantıksal durum.'],['0','int','Sıfır da bir tam sayıdır.'],['"42"','string','Rakam görünse de tırnaklar onu metin yapar.'],['1','int','C# içinde 1 otomatik olarak true değildir.'],['"false"','string','Tırnak içindeki false, bool değil metindir.'],['99','int','Adet veya skor olarak kullanılabilir.'],['true','bool','Bir koşulun doğru olduğunu taşır.']] as const;const [practice,setPractice]=useState(false);const [index,setIndex]=useState(0);const [feedback,setFeedback]=useState<{ok:boolean;text:string}|null>(null);const [done,setDone]=useState(false);const item=items[index];
  const choose=(bucket:string)=>{if(!item||done)return;if(bucket===item[1]){setFeedback({ok:true,text:copy(locale,item[2],['Unquoted whole number.','A sequence of characters in double quotes.','A two-state logical value.','Negative, but still a whole number.','Text shown to a player or developer.','A negative logical state.','Zero is also a whole number.','Quotes make it text even though it contains digits.','In C#, 1 is not automatically true.','Quoted false is text, not a bool.','Can represent a count or score.','Carries a true condition.'][index])});if(index===items.length-1){setDone(true);onComplete();}else window.setTimeout(()=>{setIndex(index+1);setFeedback(null)},520);}else setFeedback({ok:false,text:copy(locale,'Bu kutu değerin yazımıyla uyuşmuyor. Tırnakları, eksi işaretini ve `true` / `false` sözcüklerini kod gibi yeniden oku.','That bucket does not match the value’s syntax. Re-read quotes, the minus sign, and the `true` / `false` keywords as code.')});};
  if (!practice) return <><ActivityHeader eyebrow={copy(locale,'Önce öğren','Learn first')} title={copy(locale,'Veri türü, değerin ne anlama geldiğini söyler.','A data type tells us what a value means.')} body={copy(locale,'Bilgisayar `42`, `"Deniz"` ve `true` değerlerini aynı biçimde kullanamaz. Tür; saklama, karşılaştırma ve hangi işlemlerin yapılabileceği konusunda C#’a kural verir.','The computer cannot use `42`, `"Deniz"`, and `true` in the same way. A type tells C# how to store, compare, and operate on a value.')} /><div className="type-teaching"><article><span className="type-icon number">42</span><div><code>int</code><strong>{copy(locale,'Tam sayı','Whole number')}</strong><p>{copy(locale,'Adet, skor, can ve seviye gibi ondalıksız sayılar.','Counts, score, lives, and levels without decimal fractions.')}</p><pre><code><span className="syntax-keyword">int</span> coinCount = <span className="syntax-number">42</span>;</code></pre></div></article><article><span className="type-icon text">Aa</span><div><code>string</code><strong>{copy(locale,'Metin','Text')}</strong><p>{copy(locale,'İsim ve mesaj gibi karakter dizileri. Değer çift tırnak içinde yazılır.','Character sequences such as names and messages. Values use double quotes.')}</p><pre><code><span className="syntax-keyword">string</span> playerName = <span className="syntax-string">"Deniz"</span>;</code></pre></div></article><article><span className="type-icon boolean">✓</span><div><code>bool</code><strong>{copy(locale,'İki durumlu karar','Two-state decision')}</strong><p><TechnicalInline text={copy(locale,'Sadece `true` veya `false`: oyun açık mı, kapı kilitli mi?','Only `true` or `false`: is the game active, is the door locked?')} /></p><pre><code><span className="syntax-keyword">bool</span> isGameActive = <span className="syntax-boolean">true</span>;</code></pre></div></article></div><div className="game-state-example"><span className="mini-game-coin">◆</span><div><small>{copy(locale,'OYUN DURUMU','GAME STATE')}</small><p><code>coinCount</code> <b>42</b></p><p><code>playerName</code> <b>Deniz</b></p><p><code>isGameActive</code> <b>true</b></p></div><p>{copy(locale,'Aynı ekrandaki üç bilgi, üç farklı amaç taşıdığı için üç farklı tür kullanır.','Three pieces of information on one screen use three different types because they serve different purposes.')}</p></div><TeachingGate locale={locale} onOpen={()=>setPractice(true)} /></>;
  return <><ActivityHeader eyebrow={copy(locale,'Şimdi uygula','Now practise')} title={copy(locale,'Değeri doğru veri türüne gönder.','Send each value to its data type.')} body={copy(locale,'On iki kod değerini tek tek oku. Özellikle `42` ile `"42"`, `false` ile `"false"` arasındaki farkı tırnaklardan yakala.','Read twelve code values one by one. Use quotation marks to catch the difference between `42` and `"42"`, or `false` and `"false"`.')} progress={`${index+1} / ${items.length}`} />{item?<div className="sort-stage"><div className="sort-code-label">{copy(locale,'C# DEĞERİ','C# VALUE')}</div><code>{item[0]}</code><div>{['int','string','bool'].map(x=><button key={x} onClick={()=>choose(x)} disabled={done}><code>{x}</code><small>{x==='int'?copy(locale,'tam sayı','whole number'):x==='string'?copy(locale,'metin','text'):copy(locale,'doğru / yanlış','true / false')}</small></button>)}</div></div>:null}{feedback&&!done&&(feedback.ok?<Done><TechnicalInline text={feedback.text}/></Done>:<p className="activity-feedback error"><TechnicalInline text={feedback.text}/></p>)}{done&&<Done><TechnicalInline text={copy(locale,'On iki değeri kod yazımını okuyarak sınıflandırdın. Artık tür kararını yalnızca değerin görünüşüne değil, sözdizimine ve anlamına göre verebilirsin.','You classified twelve values by reading code syntax. You can now choose a type from both syntax and meaning, rather than appearance alone.')} /></Done>}</>;
}

function ConsoleDetective({ locale, onComplete }: Omit<LessonActivityProps, 'kind'>) {
  const [log,setLog]=useState<number|null>(null);const [line,setLine]=useState<number|null>(null);const logs=[['ℹ','Unity hazır','FirstScript.cs:7'],['△','`awake` callback olarak çağrılmaz','FirstScript.cs:5'],['×','CS1525 · Geçersiz ifade','FirstScript.cs:7']];
  const chooseLine=(i:number)=>{setLine(i);if(log===2&&i===6)onComplete();};
  return <><ActivityHeader eyebrow={copy(locale,'Console dedektifi','Console detective')} title={copy(locale,'Mesajdan dosyaya, dosyadan satıra git.','Move from message to file, then line.')} body={copy(locale,'Önce çalışmayı durduran kırmızı kaydı seç. Ardından verdiği dosya ve satır bilgisine göre kod satırını işaretle.','First select the red blocking record, then mark the code line using its file and line information.')} /><div className="console-lab"><div className="console-records">{logs.map((x,i)=><button key={x[1]} className={log===i?'selected':''} onClick={()=>{setLog(i);setLine(null)}}><b>{x[0]}</b><span><strong>{x[1]}</strong><small>{x[2]}</small></span></button>)}</div><ol className="mini-code-lines">{['using UnityEngine;','','public class FirstScript : MonoBehaviour','{','    void Start()','    {','        İlk mesajını buraya yaz.','    }','}'].map((x,i)=><li key={i}><button disabled={log===null} className={line===i?(log===2&&i===6?'correct':'incorrect'):''} onClick={()=>chooseLine(i)}><span>{i+1}</span><code>{x||' '}</code></button></li>)}</ol></div>{line!==null&&(log===2&&line===6?<Done>{copy(locale,'Doğru kayıt ve doğru satır. Hata mesajını rastgele değil, dosya ve konum bilgisiyle izledin.','Correct record and line. You traced the error using its file and location rather than guessing.')}</Done>:<p className="activity-feedback error">{copy(locale,'Seçtiğin kayıt veya satır eşleşmiyor. Kırmızı kaydın dosya ve satır bilgisini yeniden oku.','The record and line do not match. Read the red record’s file and line again.')}</p>)}</>;
}

function Mastery({ locale, onComplete }: Omit<LessonActivityProps, 'kind'>) {
  const questions=useMemo(()=>[
    {q:copy(locale,'`using UnityEngine;` ne yapar?','What does `using UnityEngine;` do?'),a:[copy(locale,'Unity türlerine kısa adla erişim sağlar','Allows short-name access to Unity types'),copy(locale,'Oyunu çalıştırır','Runs the game'),copy(locale,'GameObject oluşturur','Creates a GameObject')],right:0},
    {q:copy(locale,'`void awake()` neden sessiz kalabilir?','Why can `void awake()` remain silent?'),a:[copy(locale,'`void` yasaktır','`void` is forbidden'),copy(locale,'Unity tam olarak `Awake` adını bekler','Unity expects the exact name `Awake`'),copy(locale,'Comment eksiktir','A comment is missing')],right:1},
    {q:copy(locale,'Script ile Component ilişkisi hangisidir?','What is the script–Component relationship?'),a:[copy(locale,'Tamamen aynı dosyadır','They are exactly the same file'),copy(locale,'Script kaynaktır; Component derlenmiş sınıfın sahnedeki örneğidir','The script is source; the Component is a scene instance of the compiled class'),copy(locale,'Component yalnızca görseldir','A Component is only visual')],right:1},
  ],[locale]);const [q,setQ]=useState(0);const [wrong,setWrong]=useState(false);const [done,setDone]=useState(false);const current=questions[q];
  return <><ActivityHeader eyebrow={copy(locale,'Ustalık kontrolü','Mastery check')} title={done?copy(locale,'Temel model yerli yerine oturdu.','The foundation is in place.'):current.q} body={copy(locale,'Üç kısa soru. Yanlış cevap puan düşürmez; açıklamayı okuyup yeniden denersin.','Three short questions. A wrong answer does not remove points; read the feedback and try again.')} progress={`${done?3:q+1} / 3`} />{!done&&<div className="choice-list">{current.a.map((x,i)=><button key={x} onClick={()=>{if(i===current.right){setWrong(false);if(q===questions.length-1){setDone(true);onComplete();}else setQ(q+1);}else setWrong(true)}}><b>{String.fromCharCode(65+i)}</b><TechnicalInline text={x}/></button>)}</div>}{wrong&&!done&&<p className="activity-feedback error">{copy(locale,'Bu cevap kavramın görevini karşılamıyor. Terimin kod içinde neyi değiştirdiğini düşün.','This answer does not match the concept’s job. Think about what the term changes in code.')}</p>}{done?<Done>{copy(locale,'Üç soruyu tamamladın. Artık script, sınıf, Component ve Unity callback ayrımını açıklayabilirsin.','You completed all three questions and can explain scripts, classes, Components, and Unity callbacks.')}</Done>:q===questions.length-1&&!wrong&&<p className="activity-note">{copy(locale,'Son soruyu doğru yanıtladığında ders tamamlanacak.','The lesson completes when you answer the final question correctly.')}</p>}</>;
}
